//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecnoBencina.WPF.TecnoBencinaSrv {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Venta", Namespace="http://schemas.datacontract.org/2004/07/TecnoBencina.Negocio")]
    [System.SerializableAttribute()]
    public partial class Venta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TecnoBencina.WPF.TecnoBencinaSrv.Anulacion anulacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TecnoBencina.WPF.TecnoBencinaSrv.BeneficiarioCredito beneficiarioCreditoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TecnoBencina.WPF.TecnoBencinaSrv.Combustible combustibleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TecnoBencina.WPF.TecnoBencinaSrv.EstadoVenta estadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int litrosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int montoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TecnoBencina.WPF.TecnoBencinaSrv.Surtidor surtidorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TecnoBencina.WPF.TecnoBencinaSrv.Usuario usuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TecnoBencina.WPF.TecnoBencinaSrv.Vale valeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TecnoBencina.WPF.TecnoBencinaSrv.Anulacion anulacion {
            get {
                return this.anulacionField;
            }
            set {
                if ((object.ReferenceEquals(this.anulacionField, value) != true)) {
                    this.anulacionField = value;
                    this.RaisePropertyChanged("anulacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TecnoBencina.WPF.TecnoBencinaSrv.BeneficiarioCredito beneficiarioCredito {
            get {
                return this.beneficiarioCreditoField;
            }
            set {
                if ((object.ReferenceEquals(this.beneficiarioCreditoField, value) != true)) {
                    this.beneficiarioCreditoField = value;
                    this.RaisePropertyChanged("beneficiarioCredito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TecnoBencina.WPF.TecnoBencinaSrv.Combustible combustible {
            get {
                return this.combustibleField;
            }
            set {
                if ((object.ReferenceEquals(this.combustibleField, value) != true)) {
                    this.combustibleField = value;
                    this.RaisePropertyChanged("combustible");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TecnoBencina.WPF.TecnoBencinaSrv.EstadoVenta estado {
            get {
                return this.estadoField;
            }
            set {
                if ((this.estadoField.Equals(value) != true)) {
                    this.estadoField = value;
                    this.RaisePropertyChanged("estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fecha {
            get {
                return this.fechaField;
            }
            set {
                if ((this.fechaField.Equals(value) != true)) {
                    this.fechaField = value;
                    this.RaisePropertyChanged("fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int litros {
            get {
                return this.litrosField;
            }
            set {
                if ((this.litrosField.Equals(value) != true)) {
                    this.litrosField = value;
                    this.RaisePropertyChanged("litros");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int monto {
            get {
                return this.montoField;
            }
            set {
                if ((this.montoField.Equals(value) != true)) {
                    this.montoField = value;
                    this.RaisePropertyChanged("monto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TecnoBencina.WPF.TecnoBencinaSrv.Surtidor surtidor {
            get {
                return this.surtidorField;
            }
            set {
                if ((object.ReferenceEquals(this.surtidorField, value) != true)) {
                    this.surtidorField = value;
                    this.RaisePropertyChanged("surtidor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TecnoBencina.WPF.TecnoBencinaSrv.Usuario usuario {
            get {
                return this.usuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.usuarioField, value) != true)) {
                    this.usuarioField = value;
                    this.RaisePropertyChanged("usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TecnoBencina.WPF.TecnoBencinaSrv.Vale vale {
            get {
                return this.valeField;
            }
            set {
                if ((object.ReferenceEquals(this.valeField, value) != true)) {
                    this.valeField = value;
                    this.RaisePropertyChanged("vale");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Anulacion", Namespace="http://schemas.datacontract.org/2004/07/TecnoBencina.Negocio")]
    [System.SerializableAttribute()]
    public partial class Anulacion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string razonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TecnoBencina.WPF.TecnoBencinaSrv.Usuario usuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string razon {
            get {
                return this.razonField;
            }
            set {
                if ((object.ReferenceEquals(this.razonField, value) != true)) {
                    this.razonField = value;
                    this.RaisePropertyChanged("razon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TecnoBencina.WPF.TecnoBencinaSrv.Usuario usuario {
            get {
                return this.usuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.usuarioField, value) != true)) {
                    this.usuarioField = value;
                    this.RaisePropertyChanged("usuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BeneficiarioCredito", Namespace="http://schemas.datacontract.org/2004/07/TecnoBencina.Negocio")]
    [System.SerializableAttribute()]
    public partial class BeneficiarioCredito : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dvField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool estadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime limiteVigenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreEmpresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int rutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int topeLitrosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dv {
            get {
                return this.dvField;
            }
            set {
                if ((object.ReferenceEquals(this.dvField, value) != true)) {
                    this.dvField = value;
                    this.RaisePropertyChanged("dv");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool estado {
            get {
                return this.estadoField;
            }
            set {
                if ((this.estadoField.Equals(value) != true)) {
                    this.estadoField = value;
                    this.RaisePropertyChanged("estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime limiteVigencia {
            get {
                return this.limiteVigenciaField;
            }
            set {
                if ((this.limiteVigenciaField.Equals(value) != true)) {
                    this.limiteVigenciaField = value;
                    this.RaisePropertyChanged("limiteVigencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombreEmpresa {
            get {
                return this.nombreEmpresaField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreEmpresaField, value) != true)) {
                    this.nombreEmpresaField = value;
                    this.RaisePropertyChanged("nombreEmpresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int rut {
            get {
                return this.rutField;
            }
            set {
                if ((this.rutField.Equals(value) != true)) {
                    this.rutField = value;
                    this.RaisePropertyChanged("rut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int topeLitros {
            get {
                return this.topeLitrosField;
            }
            set {
                if ((this.topeLitrosField.Equals(value) != true)) {
                    this.topeLitrosField = value;
                    this.RaisePropertyChanged("topeLitros");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Combustible", Namespace="http://schemas.datacontract.org/2004/07/TecnoBencina.Negocio")]
    [System.SerializableAttribute()]
    public partial class Combustible : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal cantidadPorSurtidorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal cantidadTotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool estadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal precioActualField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal cantidadPorSurtidor {
            get {
                return this.cantidadPorSurtidorField;
            }
            set {
                if ((this.cantidadPorSurtidorField.Equals(value) != true)) {
                    this.cantidadPorSurtidorField = value;
                    this.RaisePropertyChanged("cantidadPorSurtidor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal cantidadTotal {
            get {
                return this.cantidadTotalField;
            }
            set {
                if ((this.cantidadTotalField.Equals(value) != true)) {
                    this.cantidadTotalField = value;
                    this.RaisePropertyChanged("cantidadTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool estado {
            get {
                return this.estadoField;
            }
            set {
                if ((this.estadoField.Equals(value) != true)) {
                    this.estadoField = value;
                    this.RaisePropertyChanged("estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal precioActual {
            get {
                return this.precioActualField;
            }
            set {
                if ((this.precioActualField.Equals(value) != true)) {
                    this.precioActualField = value;
                    this.RaisePropertyChanged("precioActual");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Surtidor", Namespace="http://schemas.datacontract.org/2004/07/TecnoBencina.Negocio")]
    [System.SerializableAttribute()]
    public partial class Surtidor : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TecnoBencina.WPF.TecnoBencinaSrv.Combustible[] combustiblesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool estadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TecnoBencina.WPF.TecnoBencinaSrv.Combustible[] combustibles {
            get {
                return this.combustiblesField;
            }
            set {
                if ((object.ReferenceEquals(this.combustiblesField, value) != true)) {
                    this.combustiblesField = value;
                    this.RaisePropertyChanged("combustibles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool estado {
            get {
                return this.estadoField;
            }
            set {
                if ((this.estadoField.Equals(value) != true)) {
                    this.estadoField = value;
                    this.RaisePropertyChanged("estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://schemas.datacontract.org/2004/07/TecnoBencina.Negocio")]
    [System.SerializableAttribute()]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string amaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string apatrnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dvField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool estadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TecnoBencina.WPF.TecnoBencinaSrv.Rol rolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal rutField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string amaterno {
            get {
                return this.amaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.amaternoField, value) != true)) {
                    this.amaternoField = value;
                    this.RaisePropertyChanged("amaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string apatrno {
            get {
                return this.apatrnoField;
            }
            set {
                if ((object.ReferenceEquals(this.apatrnoField, value) != true)) {
                    this.apatrnoField = value;
                    this.RaisePropertyChanged("apatrno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dv {
            get {
                return this.dvField;
            }
            set {
                if ((object.ReferenceEquals(this.dvField, value) != true)) {
                    this.dvField = value;
                    this.RaisePropertyChanged("dv");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool estado {
            get {
                return this.estadoField;
            }
            set {
                if ((this.estadoField.Equals(value) != true)) {
                    this.estadoField = value;
                    this.RaisePropertyChanged("estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombres {
            get {
                return this.nombresField;
            }
            set {
                if ((object.ReferenceEquals(this.nombresField, value) != true)) {
                    this.nombresField = value;
                    this.RaisePropertyChanged("nombres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TecnoBencina.WPF.TecnoBencinaSrv.Rol rol {
            get {
                return this.rolField;
            }
            set {
                if ((object.ReferenceEquals(this.rolField, value) != true)) {
                    this.rolField = value;
                    this.RaisePropertyChanged("rol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal rut {
            get {
                return this.rutField;
            }
            set {
                if ((this.rutField.Equals(value) != true)) {
                    this.rutField = value;
                    this.RaisePropertyChanged("rut");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Vale", Namespace="http://schemas.datacontract.org/2004/07/TecnoBencina.Negocio")]
    [System.SerializableAttribute()]
    public partial class Vale : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TecnoBencina.WPF.TecnoBencinaSrv.CantidadLitros cantidadLitrosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool estadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TecnoBencina.WPF.TecnoBencinaSrv.CantidadLitros cantidadLitros {
            get {
                return this.cantidadLitrosField;
            }
            set {
                if ((this.cantidadLitrosField.Equals(value) != true)) {
                    this.cantidadLitrosField = value;
                    this.RaisePropertyChanged("cantidadLitros");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool estado {
            get {
                return this.estadoField;
            }
            set {
                if ((this.estadoField.Equals(value) != true)) {
                    this.estadoField = value;
                    this.RaisePropertyChanged("estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EstadoVenta", Namespace="http://schemas.datacontract.org/2004/07/TecnoBencina.Negocio")]
    public enum EstadoVenta : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        sin_confirmar = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        confirmada = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        anulada = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Rol", Namespace="http://schemas.datacontract.org/2004/07/TecnoBencina.Negocio")]
    [System.SerializableAttribute()]
    public partial class Rol : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TecnoBencina.WPF.TecnoBencinaSrv.Permiso[] permisosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TecnoBencina.WPF.TecnoBencinaSrv.Permiso[] permisos {
            get {
                return this.permisosField;
            }
            set {
                if ((object.ReferenceEquals(this.permisosField, value) != true)) {
                    this.permisosField = value;
                    this.RaisePropertyChanged("permisos");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Permiso", Namespace="http://schemas.datacontract.org/2004/07/TecnoBencina.Negocio")]
    [System.SerializableAttribute()]
    public partial class Permiso : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CantidadLitros", Namespace="http://schemas.datacontract.org/2004/07/TecnoBencina.Negocio")]
    public enum CantidadLitros : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        diez = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        veinte = 20,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        treinta = 30,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Empresa", Namespace="http://schemas.datacontract.org/2004/07/TecnoBencina.Negocio")]
    [System.SerializableAttribute()]
    public partial class Empresa : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dvField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool estadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal rutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TecnoBencina.WPF.TecnoBencinaSrv.Usuario usuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dv {
            get {
                return this.dvField;
            }
            set {
                if ((object.ReferenceEquals(this.dvField, value) != true)) {
                    this.dvField = value;
                    this.RaisePropertyChanged("dv");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool estado {
            get {
                return this.estadoField;
            }
            set {
                if ((this.estadoField.Equals(value) != true)) {
                    this.estadoField = value;
                    this.RaisePropertyChanged("estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal rut {
            get {
                return this.rutField;
            }
            set {
                if ((this.rutField.Equals(value) != true)) {
                    this.rutField = value;
                    this.RaisePropertyChanged("rut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TecnoBencina.WPF.TecnoBencinaSrv.Usuario usuario {
            get {
                return this.usuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.usuarioField, value) != true)) {
                    this.usuarioField = value;
                    this.RaisePropertyChanged("usuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Talonario", Namespace="http://schemas.datacontract.org/2004/07/TecnoBencina.Negocio")]
    [System.SerializableAttribute()]
    public partial class Talonario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TecnoBencina.WPF.TecnoBencinaSrv.Empresa empresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool estadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fechaEntregaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int numComprobanteTransaccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TecnoBencina.WPF.TecnoBencinaSrv.Vale[] valesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TecnoBencina.WPF.TecnoBencinaSrv.Empresa empresa {
            get {
                return this.empresaField;
            }
            set {
                if ((object.ReferenceEquals(this.empresaField, value) != true)) {
                    this.empresaField = value;
                    this.RaisePropertyChanged("empresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool estado {
            get {
                return this.estadoField;
            }
            set {
                if ((this.estadoField.Equals(value) != true)) {
                    this.estadoField = value;
                    this.RaisePropertyChanged("estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fechaEntrega {
            get {
                return this.fechaEntregaField;
            }
            set {
                if ((this.fechaEntregaField.Equals(value) != true)) {
                    this.fechaEntregaField = value;
                    this.RaisePropertyChanged("fechaEntrega");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int numComprobanteTransaccion {
            get {
                return this.numComprobanteTransaccionField;
            }
            set {
                if ((this.numComprobanteTransaccionField.Equals(value) != true)) {
                    this.numComprobanteTransaccionField = value;
                    this.RaisePropertyChanged("numComprobanteTransaccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TecnoBencina.WPF.TecnoBencinaSrv.Vale[] vales {
            get {
                return this.valesField;
            }
            set {
                if ((object.ReferenceEquals(this.valesField, value) != true)) {
                    this.valesField = value;
                    this.RaisePropertyChanged("vales");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HistorialPrecio", Namespace="http://schemas.datacontract.org/2004/07/TecnoBencina.Negocio")]
    [System.SerializableAttribute()]
    public partial class HistorialPrecio : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TecnoBencina.WPF.TecnoBencinaSrv.Combustible combustibleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal precioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TecnoBencina.WPF.TecnoBencinaSrv.Combustible combustible {
            get {
                return this.combustibleField;
            }
            set {
                if ((object.ReferenceEquals(this.combustibleField, value) != true)) {
                    this.combustibleField = value;
                    this.RaisePropertyChanged("combustible");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fecha {
            get {
                return this.fechaField;
            }
            set {
                if ((this.fechaField.Equals(value) != true)) {
                    this.fechaField = value;
                    this.RaisePropertyChanged("fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal precio {
            get {
                return this.precioField;
            }
            set {
                if ((this.precioField.Equals(value) != true)) {
                    this.precioField = value;
                    this.RaisePropertyChanged("precio");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TecnoBencinaSrv.IServicio")]
    public interface IServicio {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarVentas", ReplyAction="http://tempuri.org/IServicio/ListarVentasResponse")]
        TecnoBencina.WPF.TecnoBencinaSrv.Venta[] ListarVentas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/BuscarVenta", ReplyAction="http://tempuri.org/IServicio/BuscarVentaResponse")]
        TecnoBencina.WPF.TecnoBencinaSrv.Venta BuscarVenta(int _id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/BuscarVentaConVale", ReplyAction="http://tempuri.org/IServicio/BuscarVentaConValeResponse")]
        TecnoBencina.WPF.TecnoBencinaSrv.Venta BuscarVentaConVale(int _idVale);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/CreateVenta", ReplyAction="http://tempuri.org/IServicio/CreateVentaResponse")]
        TecnoBencina.WPF.TecnoBencinaSrv.Venta CreateVenta(int _id, int _idSurtidor, int _litros, int _idCombustible, int _rutUsuario, int _idVale, int _idBeneficiario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/SwitchStatusVenta", ReplyAction="http://tempuri.org/IServicio/SwitchStatusVentaResponse")]
        bool SwitchStatusVenta(int _id, TecnoBencina.WPF.TecnoBencinaSrv.EstadoVenta _estado, int _rutUsuario, string _razon);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/cantLtsVendidosPorComb", ReplyAction="http://tempuri.org/IServicio/cantLtsVendidosPorCombResponse")]
        decimal cantLtsVendidosPorComb(int _idCombustible, System.DateTime _fechaInicio, System.DateTime _fechaTermino);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/cantLtsVendidosPorCombuEnSurtidor", ReplyAction="http://tempuri.org/IServicio/cantLtsVendidosPorCombuEnSurtidorResponse")]
        decimal cantLtsVendidosPorCombuEnSurtidor(int _idCombustible, int _idSurtidor, System.DateTime _fechaInicio, System.DateTime _fechaTermino);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarPermisos", ReplyAction="http://tempuri.org/IServicio/ListarPermisosResponse")]
        TecnoBencina.WPF.TecnoBencinaSrv.Permiso[] ListarPermisos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarPermisosPorRol", ReplyAction="http://tempuri.org/IServicio/ListarPermisosPorRolResponse")]
        TecnoBencina.WPF.TecnoBencinaSrv.Permiso[] ListarPermisosPorRol(int _idRol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/BuscarRol", ReplyAction="http://tempuri.org/IServicio/BuscarRolResponse")]
        TecnoBencina.WPF.TecnoBencinaSrv.Rol BuscarRol(int _id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarRoles", ReplyAction="http://tempuri.org/IServicio/ListarRolesResponse")]
        TecnoBencina.WPF.TecnoBencinaSrv.Rol[] ListarRoles();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/VerificarUsuario", ReplyAction="http://tempuri.org/IServicio/VerificarUsuarioResponse")]
        bool VerificarUsuario(int _rut, string _password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarUsuarios", ReplyAction="http://tempuri.org/IServicio/ListarUsuariosResponse")]
        TecnoBencina.WPF.TecnoBencinaSrv.Usuario[] ListarUsuarios();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/BuscarUsuario", ReplyAction="http://tempuri.org/IServicio/BuscarUsuarioResponse")]
        TecnoBencina.WPF.TecnoBencinaSrv.Usuario BuscarUsuario(int _rut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/CreateUsuario", ReplyAction="http://tempuri.org/IServicio/CreateUsuarioResponse")]
        bool CreateUsuario(int _rut, string _dv, string _nombres, string _apaterno, string _amaterno, string _password, int _rol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/UpdateUsuario", ReplyAction="http://tempuri.org/IServicio/UpdateUsuarioResponse")]
        bool UpdateUsuario(int _rut, string _nombres, string _apaterno, string _amaterno, int _rol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/SwitchStatusUsuario", ReplyAction="http://tempuri.org/IServicio/SwitchStatusUsuarioResponse")]
        bool SwitchStatusUsuario(int _rut, bool _enabled);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/UpdatePassword", ReplyAction="http://tempuri.org/IServicio/UpdatePasswordResponse")]
        bool UpdatePassword(int _rut, string _passAntigua, string _passNueva);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/hasPermission", ReplyAction="http://tempuri.org/IServicio/hasPermissionResponse")]
        bool hasPermission(int _rut, string _permission);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/hasRole", ReplyAction="http://tempuri.org/IServicio/hasRoleResponse")]
        bool hasRole(int _rut, string _role);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ValidaRut", ReplyAction="http://tempuri.org/IServicio/ValidaRutResponse")]
        bool ValidaRut(string _rut, string _dv);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarEmpresas", ReplyAction="http://tempuri.org/IServicio/ListarEmpresasResponse")]
        TecnoBencina.WPF.TecnoBencinaSrv.Empresa[] ListarEmpresas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarTalonariosPorEmpresa", ReplyAction="http://tempuri.org/IServicio/ListarTalonariosPorEmpresaResponse")]
        TecnoBencina.WPF.TecnoBencinaSrv.Talonario[] ListarTalonariosPorEmpresa(int _rutEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/BuscarEmpresa", ReplyAction="http://tempuri.org/IServicio/BuscarEmpresaResponse")]
        TecnoBencina.WPF.TecnoBencinaSrv.Empresa BuscarEmpresa(int _rut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/CreateEmpresa", ReplyAction="http://tempuri.org/IServicio/CreateEmpresaResponse")]
        bool CreateEmpresa(int _rut, string _dv, string _nombre, int _rutUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/UpdateEmpresa", ReplyAction="http://tempuri.org/IServicio/UpdateEmpresaResponse")]
        bool UpdateEmpresa(int _rut, string _nombre, int _rutUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/SwitchStatusEmpresa", ReplyAction="http://tempuri.org/IServicio/SwitchStatusEmpresaResponse")]
        bool SwitchStatusEmpresa(int _rut, bool _enabled);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarHistorialPrecio", ReplyAction="http://tempuri.org/IServicio/ListarHistorialPrecioResponse")]
        TecnoBencina.WPF.TecnoBencinaSrv.HistorialPrecio[] ListarHistorialPrecio();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarHistorialPrecioPorCombustible", ReplyAction="http://tempuri.org/IServicio/ListarHistorialPrecioPorCombustibleResponse")]
        TecnoBencina.WPF.TecnoBencinaSrv.HistorialPrecio[] ListarHistorialPrecioPorCombustible(int _idCombustible);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/BuscarHistorialPrecio", ReplyAction="http://tempuri.org/IServicio/BuscarHistorialPrecioResponse")]
        TecnoBencina.WPF.TecnoBencinaSrv.HistorialPrecio BuscarHistorialPrecio(int _id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/BuscarPrecioActualDeCombustible", ReplyAction="http://tempuri.org/IServicio/BuscarPrecioActualDeCombustibleResponse")]
        decimal BuscarPrecioActualDeCombustible(int _idCombustible);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/CreateHistorialPrecioCombustible", ReplyAction="http://tempuri.org/IServicio/CreateHistorialPrecioCombustibleResponse")]
        bool CreateHistorialPrecioCombustible(int _id, System.DateTime _fecha, decimal _precio, int _idCombustible);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/UpdateHistorialPrecioCombustible", ReplyAction="http://tempuri.org/IServicio/UpdateHistorialPrecioCombustibleResponse")]
        bool UpdateHistorialPrecioCombustible(int _id, decimal _precio, int _idCombustible);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarCombustibles", ReplyAction="http://tempuri.org/IServicio/ListarCombustiblesResponse")]
        TecnoBencina.WPF.TecnoBencinaSrv.Combustible[] ListarCombustibles();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/BuscarCombustible", ReplyAction="http://tempuri.org/IServicio/BuscarCombustibleResponse")]
        TecnoBencina.WPF.TecnoBencinaSrv.Combustible BuscarCombustible(int _idCombustible);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/BuscarCombustiblesPorSurtidor", ReplyAction="http://tempuri.org/IServicio/BuscarCombustiblesPorSurtidorResponse")]
        TecnoBencina.WPF.TecnoBencinaSrv.Combustible[] BuscarCombustiblesPorSurtidor(int _idSurtidor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/TotalLitosPorCombustible", ReplyAction="http://tempuri.org/IServicio/TotalLitosPorCombustibleResponse")]
        decimal TotalLitosPorCombustible(int _idCombustible);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/CantidadDeCombustiblePorSurtidor", ReplyAction="http://tempuri.org/IServicio/CantidadDeCombustiblePorSurtidorResponse")]
        decimal CantidadDeCombustiblePorSurtidor(int _idCombustible, int _idSurtidor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/CreateCombustible", ReplyAction="http://tempuri.org/IServicio/CreateCombustibleResponse")]
        bool CreateCombustible(int _id, string _nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/SwitchStatusCombustible", ReplyAction="http://tempuri.org/IServicio/SwitchStatusCombustibleResponse")]
        bool SwitchStatusCombustible(int _id, bool _enabled);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarSurtidores", ReplyAction="http://tempuri.org/IServicio/ListarSurtidoresResponse")]
        TecnoBencina.WPF.TecnoBencinaSrv.Surtidor[] ListarSurtidores();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/BuscarSurtidor", ReplyAction="http://tempuri.org/IServicio/BuscarSurtidorResponse")]
        TecnoBencina.WPF.TecnoBencinaSrv.Surtidor BuscarSurtidor(int _id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/CreateSurtidor", ReplyAction="http://tempuri.org/IServicio/CreateSurtidorResponse")]
        bool CreateSurtidor(int _id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/SwitchStatusSurtidor", ReplyAction="http://tempuri.org/IServicio/SwitchStatusSurtidorResponse")]
        bool SwitchStatusSurtidor(int _id, bool _enabled);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/CargarORemoverCombusible", ReplyAction="http://tempuri.org/IServicio/CargarORemoverCombusibleResponse")]
        bool CargarORemoverCombusible(int _idSurtidor, int _litros, int _idCombustible);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarTalonarios", ReplyAction="http://tempuri.org/IServicio/ListarTalonariosResponse")]
        TecnoBencina.WPF.TecnoBencinaSrv.Talonario[] ListarTalonarios();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/BuscarTalonario", ReplyAction="http://tempuri.org/IServicio/BuscarTalonarioResponse")]
        TecnoBencina.WPF.TecnoBencinaSrv.Talonario BuscarTalonario(int _id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/BuscarTalonarioDeVale", ReplyAction="http://tempuri.org/IServicio/BuscarTalonarioDeValeResponse")]
        TecnoBencina.WPF.TecnoBencinaSrv.Talonario BuscarTalonarioDeVale(int _idVale);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/CreateTalonario", ReplyAction="http://tempuri.org/IServicio/CreateTalonarioResponse")]
        bool CreateTalonario(int _id, System.DateTime _fechaEntrega, int _numComprobanteTransaccion, int _rutEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/UpdateTalonario", ReplyAction="http://tempuri.org/IServicio/UpdateTalonarioResponse")]
        bool UpdateTalonario(int _id, System.DateTime _fechaEntrega, int _numComprobanteTransaccion, int _rutEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/SwitchStatusTalonario", ReplyAction="http://tempuri.org/IServicio/SwitchStatusTalonarioResponse")]
        bool SwitchStatusTalonario(int _id, bool _enabled);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/BuscarVale", ReplyAction="http://tempuri.org/IServicio/BuscarValeResponse")]
        TecnoBencina.WPF.TecnoBencinaSrv.Vale BuscarVale(int _id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/BuscarValesPorTalonario", ReplyAction="http://tempuri.org/IServicio/BuscarValesPorTalonarioResponse")]
        TecnoBencina.WPF.TecnoBencinaSrv.Vale[] BuscarValesPorTalonario(int _idTalonario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/CreateVale", ReplyAction="http://tempuri.org/IServicio/CreateValeResponse")]
        bool CreateVale(int _id, TecnoBencina.WPF.TecnoBencinaSrv.CantidadLitros _cantLitros, int _idTalonario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/MassCreateVale", ReplyAction="http://tempuri.org/IServicio/MassCreateValeResponse")]
        bool[] MassCreateVale(TecnoBencina.WPF.TecnoBencinaSrv.CantidadLitros _cantLitros, int _idTalonario, int _cantidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/UpdateVale", ReplyAction="http://tempuri.org/IServicio/UpdateValeResponse")]
        bool UpdateVale(int _id, TecnoBencina.WPF.TecnoBencinaSrv.CantidadLitros _cantidadLitos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/SwitchStatusVale", ReplyAction="http://tempuri.org/IServicio/SwitchStatusValeResponse")]
        bool SwitchStatusVale(int _id, bool _enabled);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarBeneficiarios", ReplyAction="http://tempuri.org/IServicio/ListarBeneficiariosResponse")]
        TecnoBencina.WPF.TecnoBencinaSrv.BeneficiarioCredito[] ListarBeneficiarios();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/BuscarBeneficiario", ReplyAction="http://tempuri.org/IServicio/BuscarBeneficiarioResponse")]
        TecnoBencina.WPF.TecnoBencinaSrv.BeneficiarioCredito BuscarBeneficiario(int _id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/CreateBeneficiario", ReplyAction="http://tempuri.org/IServicio/CreateBeneficiarioResponse")]
        bool CreateBeneficiario(int _id, int _rut, string _dv, int _tope_litros, System.DateTime _limite_vigencia, string _nombreEmpresa, bool _estado, int _rol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/UpdateBeneficiario", ReplyAction="http://tempuri.org/IServicio/UpdateBeneficiarioResponse")]
        bool UpdateBeneficiario(int _id, int _tope_litros, System.DateTime _limiteVigencia, string _nombreEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/SwitchStatusBeneficiario", ReplyAction="http://tempuri.org/IServicio/SwitchStatusBeneficiarioResponse")]
        bool SwitchStatusBeneficiario(int _id, bool _enabled);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/BeneficiarioIsOverLimit", ReplyAction="http://tempuri.org/IServicio/BeneficiarioIsOverLimitResponse")]
        bool BeneficiarioIsOverLimit(int _idBeneficiario, int _cantidadLitros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarAnulaciones", ReplyAction="http://tempuri.org/IServicio/ListarAnulacionesResponse")]
        TecnoBencina.WPF.TecnoBencinaSrv.Anulacion[] ListarAnulaciones();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/BuscarAnulacion", ReplyAction="http://tempuri.org/IServicio/BuscarAnulacionResponse")]
        TecnoBencina.WPF.TecnoBencinaSrv.Anulacion BuscarAnulacion(int _id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/UpdateAnulacion", ReplyAction="http://tempuri.org/IServicio/UpdateAnulacionResponse")]
        bool UpdateAnulacion(int _id, string _razon, int _rutUsuario);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioChannel : TecnoBencina.WPF.TecnoBencinaSrv.IServicio, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioClient : System.ServiceModel.ClientBase<TecnoBencina.WPF.TecnoBencinaSrv.IServicio>, TecnoBencina.WPF.TecnoBencinaSrv.IServicio {
        
        public ServicioClient() {
        }
        
        public ServicioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TecnoBencina.WPF.TecnoBencinaSrv.Venta[] ListarVentas() {
            return base.Channel.ListarVentas();
        }
        
        public TecnoBencina.WPF.TecnoBencinaSrv.Venta BuscarVenta(int _id) {
            return base.Channel.BuscarVenta(_id);
        }
        
        public TecnoBencina.WPF.TecnoBencinaSrv.Venta BuscarVentaConVale(int _idVale) {
            return base.Channel.BuscarVentaConVale(_idVale);
        }
        
        public TecnoBencina.WPF.TecnoBencinaSrv.Venta CreateVenta(int _id, int _idSurtidor, int _litros, int _idCombustible, int _rutUsuario, int _idVale, int _idBeneficiario) {
            return base.Channel.CreateVenta(_id, _idSurtidor, _litros, _idCombustible, _rutUsuario, _idVale, _idBeneficiario);
        }
        
        public bool SwitchStatusVenta(int _id, TecnoBencina.WPF.TecnoBencinaSrv.EstadoVenta _estado, int _rutUsuario, string _razon) {
            return base.Channel.SwitchStatusVenta(_id, _estado, _rutUsuario, _razon);
        }
        
        public decimal cantLtsVendidosPorComb(int _idCombustible, System.DateTime _fechaInicio, System.DateTime _fechaTermino) {
            return base.Channel.cantLtsVendidosPorComb(_idCombustible, _fechaInicio, _fechaTermino);
        }
        
        public decimal cantLtsVendidosPorCombuEnSurtidor(int _idCombustible, int _idSurtidor, System.DateTime _fechaInicio, System.DateTime _fechaTermino) {
            return base.Channel.cantLtsVendidosPorCombuEnSurtidor(_idCombustible, _idSurtidor, _fechaInicio, _fechaTermino);
        }
        
        public TecnoBencina.WPF.TecnoBencinaSrv.Permiso[] ListarPermisos() {
            return base.Channel.ListarPermisos();
        }
        
        public TecnoBencina.WPF.TecnoBencinaSrv.Permiso[] ListarPermisosPorRol(int _idRol) {
            return base.Channel.ListarPermisosPorRol(_idRol);
        }
        
        public TecnoBencina.WPF.TecnoBencinaSrv.Rol BuscarRol(int _id) {
            return base.Channel.BuscarRol(_id);
        }
        
        public TecnoBencina.WPF.TecnoBencinaSrv.Rol[] ListarRoles() {
            return base.Channel.ListarRoles();
        }
        
        public bool VerificarUsuario(int _rut, string _password) {
            return base.Channel.VerificarUsuario(_rut, _password);
        }
        
        public TecnoBencina.WPF.TecnoBencinaSrv.Usuario[] ListarUsuarios() {
            return base.Channel.ListarUsuarios();
        }
        
        public TecnoBencina.WPF.TecnoBencinaSrv.Usuario BuscarUsuario(int _rut) {
            return base.Channel.BuscarUsuario(_rut);
        }
        
        public bool CreateUsuario(int _rut, string _dv, string _nombres, string _apaterno, string _amaterno, string _password, int _rol) {
            return base.Channel.CreateUsuario(_rut, _dv, _nombres, _apaterno, _amaterno, _password, _rol);
        }
        
        public bool UpdateUsuario(int _rut, string _nombres, string _apaterno, string _amaterno, int _rol) {
            return base.Channel.UpdateUsuario(_rut, _nombres, _apaterno, _amaterno, _rol);
        }
        
        public bool SwitchStatusUsuario(int _rut, bool _enabled) {
            return base.Channel.SwitchStatusUsuario(_rut, _enabled);
        }
        
        public bool UpdatePassword(int _rut, string _passAntigua, string _passNueva) {
            return base.Channel.UpdatePassword(_rut, _passAntigua, _passNueva);
        }
        
        public bool hasPermission(int _rut, string _permission) {
            return base.Channel.hasPermission(_rut, _permission);
        }
        
        public bool hasRole(int _rut, string _role) {
            return base.Channel.hasRole(_rut, _role);
        }
        
        public bool ValidaRut(string _rut, string _dv) {
            return base.Channel.ValidaRut(_rut, _dv);
        }
        
        public TecnoBencina.WPF.TecnoBencinaSrv.Empresa[] ListarEmpresas() {
            return base.Channel.ListarEmpresas();
        }
        
        public TecnoBencina.WPF.TecnoBencinaSrv.Talonario[] ListarTalonariosPorEmpresa(int _rutEmpresa) {
            return base.Channel.ListarTalonariosPorEmpresa(_rutEmpresa);
        }
        
        public TecnoBencina.WPF.TecnoBencinaSrv.Empresa BuscarEmpresa(int _rut) {
            return base.Channel.BuscarEmpresa(_rut);
        }
        
        public bool CreateEmpresa(int _rut, string _dv, string _nombre, int _rutUsuario) {
            return base.Channel.CreateEmpresa(_rut, _dv, _nombre, _rutUsuario);
        }
        
        public bool UpdateEmpresa(int _rut, string _nombre, int _rutUsuario) {
            return base.Channel.UpdateEmpresa(_rut, _nombre, _rutUsuario);
        }
        
        public bool SwitchStatusEmpresa(int _rut, bool _enabled) {
            return base.Channel.SwitchStatusEmpresa(_rut, _enabled);
        }
        
        public TecnoBencina.WPF.TecnoBencinaSrv.HistorialPrecio[] ListarHistorialPrecio() {
            return base.Channel.ListarHistorialPrecio();
        }
        
        public TecnoBencina.WPF.TecnoBencinaSrv.HistorialPrecio[] ListarHistorialPrecioPorCombustible(int _idCombustible) {
            return base.Channel.ListarHistorialPrecioPorCombustible(_idCombustible);
        }
        
        public TecnoBencina.WPF.TecnoBencinaSrv.HistorialPrecio BuscarHistorialPrecio(int _id) {
            return base.Channel.BuscarHistorialPrecio(_id);
        }
        
        public decimal BuscarPrecioActualDeCombustible(int _idCombustible) {
            return base.Channel.BuscarPrecioActualDeCombustible(_idCombustible);
        }
        
        public bool CreateHistorialPrecioCombustible(int _id, System.DateTime _fecha, decimal _precio, int _idCombustible) {
            return base.Channel.CreateHistorialPrecioCombustible(_id, _fecha, _precio, _idCombustible);
        }
        
        public bool UpdateHistorialPrecioCombustible(int _id, decimal _precio, int _idCombustible) {
            return base.Channel.UpdateHistorialPrecioCombustible(_id, _precio, _idCombustible);
        }
        
        public TecnoBencina.WPF.TecnoBencinaSrv.Combustible[] ListarCombustibles() {
            return base.Channel.ListarCombustibles();
        }
        
        public TecnoBencina.WPF.TecnoBencinaSrv.Combustible BuscarCombustible(int _idCombustible) {
            return base.Channel.BuscarCombustible(_idCombustible);
        }
        
        public TecnoBencina.WPF.TecnoBencinaSrv.Combustible[] BuscarCombustiblesPorSurtidor(int _idSurtidor) {
            return base.Channel.BuscarCombustiblesPorSurtidor(_idSurtidor);
        }
        
        public decimal TotalLitosPorCombustible(int _idCombustible) {
            return base.Channel.TotalLitosPorCombustible(_idCombustible);
        }
        
        public decimal CantidadDeCombustiblePorSurtidor(int _idCombustible, int _idSurtidor) {
            return base.Channel.CantidadDeCombustiblePorSurtidor(_idCombustible, _idSurtidor);
        }
        
        public bool CreateCombustible(int _id, string _nombre) {
            return base.Channel.CreateCombustible(_id, _nombre);
        }
        
        public bool SwitchStatusCombustible(int _id, bool _enabled) {
            return base.Channel.SwitchStatusCombustible(_id, _enabled);
        }
        
        public TecnoBencina.WPF.TecnoBencinaSrv.Surtidor[] ListarSurtidores() {
            return base.Channel.ListarSurtidores();
        }
        
        public TecnoBencina.WPF.TecnoBencinaSrv.Surtidor BuscarSurtidor(int _id) {
            return base.Channel.BuscarSurtidor(_id);
        }
        
        public bool CreateSurtidor(int _id) {
            return base.Channel.CreateSurtidor(_id);
        }
        
        public bool SwitchStatusSurtidor(int _id, bool _enabled) {
            return base.Channel.SwitchStatusSurtidor(_id, _enabled);
        }
        
        public bool CargarORemoverCombusible(int _idSurtidor, int _litros, int _idCombustible) {
            return base.Channel.CargarORemoverCombusible(_idSurtidor, _litros, _idCombustible);
        }
        
        public TecnoBencina.WPF.TecnoBencinaSrv.Talonario[] ListarTalonarios() {
            return base.Channel.ListarTalonarios();
        }
        
        public TecnoBencina.WPF.TecnoBencinaSrv.Talonario BuscarTalonario(int _id) {
            return base.Channel.BuscarTalonario(_id);
        }
        
        public TecnoBencina.WPF.TecnoBencinaSrv.Talonario BuscarTalonarioDeVale(int _idVale) {
            return base.Channel.BuscarTalonarioDeVale(_idVale);
        }
        
        public bool CreateTalonario(int _id, System.DateTime _fechaEntrega, int _numComprobanteTransaccion, int _rutEmpresa) {
            return base.Channel.CreateTalonario(_id, _fechaEntrega, _numComprobanteTransaccion, _rutEmpresa);
        }
        
        public bool UpdateTalonario(int _id, System.DateTime _fechaEntrega, int _numComprobanteTransaccion, int _rutEmpresa) {
            return base.Channel.UpdateTalonario(_id, _fechaEntrega, _numComprobanteTransaccion, _rutEmpresa);
        }
        
        public bool SwitchStatusTalonario(int _id, bool _enabled) {
            return base.Channel.SwitchStatusTalonario(_id, _enabled);
        }
        
        public TecnoBencina.WPF.TecnoBencinaSrv.Vale BuscarVale(int _id) {
            return base.Channel.BuscarVale(_id);
        }
        
        public TecnoBencina.WPF.TecnoBencinaSrv.Vale[] BuscarValesPorTalonario(int _idTalonario) {
            return base.Channel.BuscarValesPorTalonario(_idTalonario);
        }
        
        public bool CreateVale(int _id, TecnoBencina.WPF.TecnoBencinaSrv.CantidadLitros _cantLitros, int _idTalonario) {
            return base.Channel.CreateVale(_id, _cantLitros, _idTalonario);
        }
        
        public bool[] MassCreateVale(TecnoBencina.WPF.TecnoBencinaSrv.CantidadLitros _cantLitros, int _idTalonario, int _cantidad) {
            return base.Channel.MassCreateVale(_cantLitros, _idTalonario, _cantidad);
        }
        
        public bool UpdateVale(int _id, TecnoBencina.WPF.TecnoBencinaSrv.CantidadLitros _cantidadLitos) {
            return base.Channel.UpdateVale(_id, _cantidadLitos);
        }
        
        public bool SwitchStatusVale(int _id, bool _enabled) {
            return base.Channel.SwitchStatusVale(_id, _enabled);
        }
        
        public TecnoBencina.WPF.TecnoBencinaSrv.BeneficiarioCredito[] ListarBeneficiarios() {
            return base.Channel.ListarBeneficiarios();
        }
        
        public TecnoBencina.WPF.TecnoBencinaSrv.BeneficiarioCredito BuscarBeneficiario(int _id) {
            return base.Channel.BuscarBeneficiario(_id);
        }
        
        public bool CreateBeneficiario(int _id, int _rut, string _dv, int _tope_litros, System.DateTime _limite_vigencia, string _nombreEmpresa, bool _estado, int _rol) {
            return base.Channel.CreateBeneficiario(_id, _rut, _dv, _tope_litros, _limite_vigencia, _nombreEmpresa, _estado, _rol);
        }
        
        public bool UpdateBeneficiario(int _id, int _tope_litros, System.DateTime _limiteVigencia, string _nombreEmpresa) {
            return base.Channel.UpdateBeneficiario(_id, _tope_litros, _limiteVigencia, _nombreEmpresa);
        }
        
        public bool SwitchStatusBeneficiario(int _id, bool _enabled) {
            return base.Channel.SwitchStatusBeneficiario(_id, _enabled);
        }
        
        public bool BeneficiarioIsOverLimit(int _idBeneficiario, int _cantidadLitros) {
            return base.Channel.BeneficiarioIsOverLimit(_idBeneficiario, _cantidadLitros);
        }
        
        public TecnoBencina.WPF.TecnoBencinaSrv.Anulacion[] ListarAnulaciones() {
            return base.Channel.ListarAnulaciones();
        }
        
        public TecnoBencina.WPF.TecnoBencinaSrv.Anulacion BuscarAnulacion(int _id) {
            return base.Channel.BuscarAnulacion(_id);
        }
        
        public bool UpdateAnulacion(int _id, string _razon, int _rutUsuario) {
            return base.Channel.UpdateAnulacion(_id, _razon, _rutUsuario);
        }
    }
}
