//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banco.Web.BancoSvc {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BancoSvc.IBancoServ")]
    public interface IBancoServ {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBancoServ/VerificarCliente", ReplyAction="http://tempuri.org/IBancoServ/VerificarClienteResponse")]
        bool VerificarCliente(string _rut, string _password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBancoServ/buscarTransferenciasPorCliente", ReplyAction="http://tempuri.org/IBancoServ/buscarTransferenciasPorClienteResponse")]
        System.Collections.Generic.List<Banco.Negocio.Transferencia> buscarTransferenciasPorCliente(string _rut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBancoServ/buscarCliente", ReplyAction="http://tempuri.org/IBancoServ/buscarClienteResponse")]
        Banco.Negocio.Cliente buscarCliente(string _rut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBancoServ/AgergarTransferencia", ReplyAction="http://tempuri.org/IBancoServ/AgergarTransferenciaResponse")]
        bool AgergarTransferencia(int _idTransferencia, string _rutCliente, string _rutDestinatario, int _nroCuentaDestinatario, int _monto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBancoServ/UpdateNombreUsuario", ReplyAction="http://tempuri.org/IBancoServ/UpdateNombreUsuarioResponse")]
        bool UpdateNombreUsuario(string _rutUsuario, string _nombreCompleto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBancoServ/EliminarTransferencia", ReplyAction="http://tempuri.org/IBancoServ/EliminarTransferenciaResponse")]
        bool EliminarTransferencia(int _idTransferencia);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBancoServChannel : Banco.Web.BancoSvc.IBancoServ, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BancoServClient : System.ServiceModel.ClientBase<Banco.Web.BancoSvc.IBancoServ>, Banco.Web.BancoSvc.IBancoServ {
        
        public BancoServClient() {
        }
        
        public BancoServClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BancoServClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BancoServClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BancoServClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool VerificarCliente(string _rut, string _password) {
            return base.Channel.VerificarCliente(_rut, _password);
        }
        
        public System.Collections.Generic.List<Banco.Negocio.Transferencia> buscarTransferenciasPorCliente(string _rut) {
            return base.Channel.buscarTransferenciasPorCliente(_rut);
        }
        
        public Banco.Negocio.Cliente buscarCliente(string _rut) {
            return base.Channel.buscarCliente(_rut);
        }
        
        public bool AgergarTransferencia(int _idTransferencia, string _rutCliente, string _rutDestinatario, int _nroCuentaDestinatario, int _monto) {
            return base.Channel.AgergarTransferencia(_idTransferencia, _rutCliente, _rutDestinatario, _nroCuentaDestinatario, _monto);
        }
        
        public bool UpdateNombreUsuario(string _rutUsuario, string _nombreCompleto) {
            return base.Channel.UpdateNombreUsuario(_rutUsuario, _nombreCompleto);
        }
        
        public bool EliminarTransferencia(int _idTransferencia) {
            return base.Channel.EliminarTransferencia(_idTransferencia);
        }
    }
}
