//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region Metadatos de relaciones en EDM

[assembly: EdmRelationshipAttribute("BancoModel", "Cliente_Transferencia_FK1", "Cliente", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Banco.DALC.Cliente), "Transferencia", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Banco.DALC.Transferencia), true)]

#endregion

namespace Banco.DALC
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class BancoEntities : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto BancoEntities usando la cadena de conexión encontrada en la sección 'BancoEntities' del archivo de configuración de la aplicación.
        /// </summary>
        public BancoEntities() : base("name=BancoEntities", "BancoEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto BancoEntities.
        /// </summary>
        public BancoEntities(string connectionString) : base(connectionString, "BancoEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto BancoEntities.
        /// </summary>
        public BancoEntities(EntityConnection connection) : base(connection, "BancoEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Cliente> Cliente
        {
            get
            {
                if ((_Cliente == null))
                {
                    _Cliente = base.CreateObjectSet<Cliente>("Cliente");
                }
                return _Cliente;
            }
        }
        private ObjectSet<Cliente> _Cliente;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Transferencia> Transferencia
        {
            get
            {
                if ((_Transferencia == null))
                {
                    _Transferencia = base.CreateObjectSet<Transferencia>("Transferencia");
                }
                return _Transferencia;
            }
        }
        private ObjectSet<Transferencia> _Transferencia;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Cliente. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToCliente(Cliente cliente)
        {
            base.AddObject("Cliente", cliente);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Transferencia. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToTransferencia(Transferencia transferencia)
        {
            base.AddObject("Transferencia", transferencia);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BancoModel", Name="Cliente")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Cliente : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Cliente.
        /// </summary>
        /// <param name="rutCliente">Valor inicial de la propiedad RutCliente.</param>
        /// <param name="nombreCompleto">Valor inicial de la propiedad NombreCompleto.</param>
        /// <param name="password">Valor inicial de la propiedad Password.</param>
        public static Cliente CreateCliente(global::System.String rutCliente, global::System.String nombreCompleto, global::System.String password)
        {
            Cliente cliente = new Cliente();
            cliente.RutCliente = rutCliente;
            cliente.NombreCompleto = nombreCompleto;
            cliente.Password = password;
            return cliente;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RutCliente
        {
            get
            {
                return _RutCliente;
            }
            set
            {
                if (_RutCliente != value)
                {
                    OnRutClienteChanging(value);
                    ReportPropertyChanging("RutCliente");
                    _RutCliente = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("RutCliente");
                    OnRutClienteChanged();
                }
            }
        }
        private global::System.String _RutCliente;
        partial void OnRutClienteChanging(global::System.String value);
        partial void OnRutClienteChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NombreCompleto
        {
            get
            {
                return _NombreCompleto;
            }
            set
            {
                OnNombreCompletoChanging(value);
                ReportPropertyChanging("NombreCompleto");
                _NombreCompleto = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NombreCompleto");
                OnNombreCompletoChanged();
            }
        }
        private global::System.String _NombreCompleto;
        partial void OnNombreCompletoChanging(global::System.String value);
        partial void OnNombreCompletoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BancoModel", "Cliente_Transferencia_FK1", "Transferencia")]
        public EntityCollection<Transferencia> Transferencia
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Transferencia>("BancoModel.Cliente_Transferencia_FK1", "Transferencia");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Transferencia>("BancoModel.Cliente_Transferencia_FK1", "Transferencia", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BancoModel", Name="Transferencia")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Transferencia : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Transferencia.
        /// </summary>
        /// <param name="idTransferencia">Valor inicial de la propiedad IdTransferencia.</param>
        /// <param name="cliente">Valor inicial de la propiedad Cliente.</param>
        /// <param name="rutDestinatario">Valor inicial de la propiedad RutDestinatario.</param>
        /// <param name="nroCuentaDestinatario">Valor inicial de la propiedad NroCuentaDestinatario.</param>
        /// <param name="monto">Valor inicial de la propiedad Monto.</param>
        public static Transferencia CreateTransferencia(global::System.Int32 idTransferencia, global::System.String cliente, global::System.String rutDestinatario, global::System.Int32 nroCuentaDestinatario, global::System.Int32 monto)
        {
            Transferencia transferencia = new Transferencia();
            transferencia.IdTransferencia = idTransferencia;
            transferencia.Cliente = cliente;
            transferencia.RutDestinatario = rutDestinatario;
            transferencia.NroCuentaDestinatario = nroCuentaDestinatario;
            transferencia.Monto = monto;
            return transferencia;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdTransferencia
        {
            get
            {
                return _IdTransferencia;
            }
            set
            {
                if (_IdTransferencia != value)
                {
                    OnIdTransferenciaChanging(value);
                    ReportPropertyChanging("IdTransferencia");
                    _IdTransferencia = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdTransferencia");
                    OnIdTransferenciaChanged();
                }
            }
        }
        private global::System.Int32 _IdTransferencia;
        partial void OnIdTransferenciaChanging(global::System.Int32 value);
        partial void OnIdTransferenciaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Cliente
        {
            get
            {
                return _Cliente;
            }
            set
            {
                OnClienteChanging(value);
                ReportPropertyChanging("Cliente");
                _Cliente = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Cliente");
                OnClienteChanged();
            }
        }
        private global::System.String _Cliente;
        partial void OnClienteChanging(global::System.String value);
        partial void OnClienteChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RutDestinatario
        {
            get
            {
                return _RutDestinatario;
            }
            set
            {
                OnRutDestinatarioChanging(value);
                ReportPropertyChanging("RutDestinatario");
                _RutDestinatario = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("RutDestinatario");
                OnRutDestinatarioChanged();
            }
        }
        private global::System.String _RutDestinatario;
        partial void OnRutDestinatarioChanging(global::System.String value);
        partial void OnRutDestinatarioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 NroCuentaDestinatario
        {
            get
            {
                return _NroCuentaDestinatario;
            }
            set
            {
                OnNroCuentaDestinatarioChanging(value);
                ReportPropertyChanging("NroCuentaDestinatario");
                _NroCuentaDestinatario = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NroCuentaDestinatario");
                OnNroCuentaDestinatarioChanged();
            }
        }
        private global::System.Int32 _NroCuentaDestinatario;
        partial void OnNroCuentaDestinatarioChanging(global::System.Int32 value);
        partial void OnNroCuentaDestinatarioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Monto
        {
            get
            {
                return _Monto;
            }
            set
            {
                OnMontoChanging(value);
                ReportPropertyChanging("Monto");
                _Monto = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Monto");
                OnMontoChanged();
            }
        }
        private global::System.Int32 _Monto;
        partial void OnMontoChanging(global::System.Int32 value);
        partial void OnMontoChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BancoModel", "Cliente_Transferencia_FK1", "Cliente")]
        public Cliente Cliente1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cliente>("BancoModel.Cliente_Transferencia_FK1", "Cliente").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cliente>("BancoModel.Cliente_Transferencia_FK1", "Cliente").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Cliente> Cliente1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cliente>("BancoModel.Cliente_Transferencia_FK1", "Cliente");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Cliente>("BancoModel.Cliente_Transferencia_FK1", "Cliente", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
