package cl.fap.tecnobencina.clases.service;




//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.5.6.0
//
// Created by Quasar Development at 15/06/2016
//
//---------------------------------------------------


import java.math.BigDecimal;


import org.ksoap2.HeaderProperty;
import org.ksoap2.serialization.*;
import org.ksoap2.transport.*;
import org.kxml2.kdom.Element;

import java.lang.reflect.Constructor;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;


public class MOCBasicHttpBinding_IServicio
{
    interface MOCIWcfMethod
    {
        MOCExtendedSoapSerializationEnvelope CreateSoapEnvelope() throws java.lang.Exception;

        java.lang.Object ProcessResult(MOCExtendedSoapSerializationEnvelope __envelope,java.lang.Object result) throws java.lang.Exception;
    }

    String url="http://intranet.tecnobencina.cl/tecnobencina/Servicio.svc";

    int timeOut=60000;
    public List< HeaderProperty> httpHeaders;
    public boolean enableLogging;

    MOCIServiceEvents callback;
    public MOCBasicHttpBinding_IServicio(){}

    public MOCBasicHttpBinding_IServicio (MOCIServiceEvents callback)
    {
        this.callback = callback;
    }
    public MOCBasicHttpBinding_IServicio(MOCIServiceEvents callback,String url)
    {
        this.callback = callback;
        this.url = url;
    }

    public MOCBasicHttpBinding_IServicio(MOCIServiceEvents callback,String url,int timeOut)
    {
        this.callback = callback;
        this.url = url;
        this.timeOut=timeOut;
    }

    protected org.ksoap2.transport.Transport createTransport()
    {
        try
        {
            java.net.URI uri = new java.net.URI(url);
            if(uri.getScheme().equalsIgnoreCase("https"))
            {
                int port=uri.getPort()>0?uri.getPort():443;
                return new HttpsTransportSE(uri.getHost(), port, uri.getPath(), timeOut);
            }
            else
            {
                return new HttpTransportSE(url,timeOut);
            }

        }
        catch (java.net.URISyntaxException e)
        {
        }
        return null;
    }
    
    protected MOCExtendedSoapSerializationEnvelope createEnvelope()
    {
        MOCExtendedSoapSerializationEnvelope envelope= new MOCExtendedSoapSerializationEnvelope(MOCExtendedSoapSerializationEnvelope.VER11);
        return envelope;
    }
    
    protected java.util.List sendRequest(String methodName,MOCExtendedSoapSerializationEnvelope envelope,org.ksoap2.transport.Transport transport  )throws java.lang.Exception
    {
        return transport.call(methodName, envelope, httpHeaders);
    }

    java.lang.Object getResult(java.lang.Class destObj,java.lang.Object source,String resultName,MOCExtendedSoapSerializationEnvelope __envelope) throws java.lang.Exception
    {
        if(source==null)
        {
            return null;
        }
        if(source instanceof SoapPrimitive)
        {
            SoapPrimitive soap =(SoapPrimitive)source;
            if(soap.getName().equals(resultName))
            {
                java.lang.Object instance=__envelope.get(source,destObj);
                return instance;
            }
        }
        else
        {
            SoapObject soap = (SoapObject)source;
            if (soap.hasProperty(resultName))
            {
                java.lang.Object j=soap.getProperty(resultName);
                if(j==null)
                {
                    return null;
                }
                java.lang.Object instance=__envelope.get(j,destObj);
                return instance;
            }
            else if( soap.getName().equals(resultName)) {
                java.lang.Object instance=__envelope.get(source,destObj);
                return instance;
            }
       }

       return null;
    }

        
    public MOCArrayOfVenta ListarVentas( ) throws java.lang.Exception
    {
        return (MOCArrayOfVenta)execute(new MOCIWcfMethod()
        {
            @Override
            public MOCExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              MOCExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "ListarVentas");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(MOCExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (MOCArrayOfVenta)getResult(MOCArrayOfVenta.class,__result,"ListarVentasResult",__envelope);
            }
        },"http://tempuri.org/IServicio/ListarVentas");
    }
    
    public android.os.AsyncTask< Void, Void, MOCOperationResult< MOCArrayOfVenta>> ListarVentasAsync()
    {
        return executeAsync(new MOCFunctions.IFunc< MOCArrayOfVenta>() {
            public MOCArrayOfVenta Func() throws java.lang.Exception {
                return ListarVentas( );
            }
        });
    }
    
    public MOCVenta BuscarVenta(final Integer _id ) throws java.lang.Exception
    {
        return (MOCVenta)execute(new MOCIWcfMethod()
        {
            @Override
            public MOCExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              MOCExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "BuscarVenta");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="_id";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(_id!=null?_id:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(MOCExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (MOCVenta)getResult(MOCVenta.class,__result,"BuscarVentaResult",__envelope);
            }
        },"http://tempuri.org/IServicio/BuscarVenta");
    }
    
    public android.os.AsyncTask< Void, Void, MOCOperationResult< MOCVenta>> BuscarVentaAsync(final Integer _id)
    {
        return executeAsync(new MOCFunctions.IFunc< MOCVenta>() {
            public MOCVenta Func() throws java.lang.Exception {
                return BuscarVenta( _id);
            }
        });
    }
    
    public MOCVenta BuscarVentaConVale(final Integer _idVale ) throws java.lang.Exception
    {
        return (MOCVenta)execute(new MOCIWcfMethod()
        {
            @Override
            public MOCExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              MOCExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "BuscarVentaConVale");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="_idVale";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(_idVale!=null?_idVale:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(MOCExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (MOCVenta)getResult(MOCVenta.class,__result,"BuscarVentaConValeResult",__envelope);
            }
        },"http://tempuri.org/IServicio/BuscarVentaConVale");
    }
    
    public android.os.AsyncTask< Void, Void, MOCOperationResult< MOCVenta>> BuscarVentaConValeAsync(final Integer _idVale)
    {
        return executeAsync(new MOCFunctions.IFunc< MOCVenta>() {
            public MOCVenta Func() throws java.lang.Exception {
                return BuscarVentaConVale( _idVale);
            }
        });
    }
    
    public MOCVenta CreateVenta(final Integer _id,final Integer _idSurtidor,final Integer _litros,final Integer _idCombustible,final Integer _rutUsuario,final Integer _idVale,final Integer _idBeneficiario ) throws java.lang.Exception
    {
        return (MOCVenta)execute(new MOCIWcfMethod()
        {
            @Override
            public MOCExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              MOCExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "CreateVenta");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="_id";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(_id!=null?_id:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="_idSurtidor";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(_idSurtidor!=null?_idSurtidor:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="_litros";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(_litros!=null?_litros:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="_idCombustible";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(_idCombustible!=null?_idCombustible:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="_rutUsuario";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(_rutUsuario!=null?_rutUsuario:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="_idVale";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(_idVale!=null?_idVale:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="_idBeneficiario";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(_idBeneficiario!=null?_idBeneficiario:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(MOCExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (MOCVenta)getResult(MOCVenta.class,__result,"CreateVentaResult",__envelope);
            }
        },"http://tempuri.org/IServicio/CreateVenta");
    }
    
    public android.os.AsyncTask< Void, Void, MOCOperationResult< MOCVenta>> CreateVentaAsync(final Integer _id,final Integer _idSurtidor,final Integer _litros,final Integer _idCombustible,final Integer _rutUsuario,final Integer _idVale,final Integer _idBeneficiario)
    {
        return executeAsync(new MOCFunctions.IFunc< MOCVenta>() {
            public MOCVenta Func() throws java.lang.Exception {
                return CreateVenta( _id,_idSurtidor,_litros,_idCombustible,_rutUsuario,_idVale,_idBeneficiario);
            }
        });
    }
    
    public Boolean SwitchStatusVenta(final Integer _id,final MOCEnums.EstadoVenta _estado,final Integer _rutUsuario,final String _razon ) throws java.lang.Exception
    {
        return (Boolean)execute(new MOCIWcfMethod()
        {
            @Override
            public MOCExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              MOCExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "SwitchStatusVenta");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="_id";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(_id!=null?_id:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="_estado";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(_estado!=null?_estado.toString():SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="_rutUsuario";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(_rutUsuario!=null?_rutUsuario:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="_razon";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(_razon!=null?_razon:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(MOCExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                SoapObject __soap=(SoapObject)__result;
                java.lang.Object obj = __soap.getProperty("SwitchStatusVentaResult");
                if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    return new Boolean(j.toString());
                }
                else if (obj!= null && obj instanceof Boolean){
                    return (Boolean)obj;
                }
                return null;
            }
        },"http://tempuri.org/IServicio/SwitchStatusVenta");
    }
    
    public android.os.AsyncTask< Void, Void, MOCOperationResult< Boolean>> SwitchStatusVentaAsync(final Integer _id,final MOCEnums.EstadoVenta _estado,final Integer _rutUsuario,final String _razon)
    {
        return executeAsync(new MOCFunctions.IFunc< Boolean>() {
            public Boolean Func() throws java.lang.Exception {
                return SwitchStatusVenta( _id,_estado,_rutUsuario,_razon);
            }
        });
    }
    
    public MOCArrayOfPermiso ListarPermisos( ) throws java.lang.Exception
    {
        return (MOCArrayOfPermiso)execute(new MOCIWcfMethod()
        {
            @Override
            public MOCExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              MOCExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "ListarPermisos");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(MOCExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (MOCArrayOfPermiso)getResult(MOCArrayOfPermiso.class,__result,"ListarPermisosResult",__envelope);
            }
        },"http://tempuri.org/IServicio/ListarPermisos");
    }
    
    public android.os.AsyncTask< Void, Void, MOCOperationResult< MOCArrayOfPermiso>> ListarPermisosAsync()
    {
        return executeAsync(new MOCFunctions.IFunc< MOCArrayOfPermiso>() {
            public MOCArrayOfPermiso Func() throws java.lang.Exception {
                return ListarPermisos( );
            }
        });
    }
    
    public MOCArrayOfPermiso ListarPermisosPorRol(final Integer _idRol ) throws java.lang.Exception
    {
        return (MOCArrayOfPermiso)execute(new MOCIWcfMethod()
        {
            @Override
            public MOCExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              MOCExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "ListarPermisosPorRol");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="_idRol";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(_idRol!=null?_idRol:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(MOCExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (MOCArrayOfPermiso)getResult(MOCArrayOfPermiso.class,__result,"ListarPermisosPorRolResult",__envelope);
            }
        },"http://tempuri.org/IServicio/ListarPermisosPorRol");
    }
    
    public android.os.AsyncTask< Void, Void, MOCOperationResult< MOCArrayOfPermiso>> ListarPermisosPorRolAsync(final Integer _idRol)
    {
        return executeAsync(new MOCFunctions.IFunc< MOCArrayOfPermiso>() {
            public MOCArrayOfPermiso Func() throws java.lang.Exception {
                return ListarPermisosPorRol( _idRol);
            }
        });
    }
    
    public MOCRol BuscarRol(final Integer _id ) throws java.lang.Exception
    {
        return (MOCRol)execute(new MOCIWcfMethod()
        {
            @Override
            public MOCExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              MOCExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "BuscarRol");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="_id";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(_id!=null?_id:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(MOCExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (MOCRol)getResult(MOCRol.class,__result,"BuscarRolResult",__envelope);
            }
        },"http://tempuri.org/IServicio/BuscarRol");
    }
    
    public android.os.AsyncTask< Void, Void, MOCOperationResult< MOCRol>> BuscarRolAsync(final Integer _id)
    {
        return executeAsync(new MOCFunctions.IFunc< MOCRol>() {
            public MOCRol Func() throws java.lang.Exception {
                return BuscarRol( _id);
            }
        });
    }
    
    public Boolean VerificarUsuario(final Integer _rut,final String _password ) throws java.lang.Exception
    {
        return (Boolean)execute(new MOCIWcfMethod()
        {
            @Override
            public MOCExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              MOCExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "VerificarUsuario");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="_rut";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(_rut!=null?_rut:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="_password";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(_password!=null?_password:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(MOCExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                SoapObject __soap=(SoapObject)__result;
                java.lang.Object obj = __soap.getProperty("VerificarUsuarioResult");
                if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    return new Boolean(j.toString());
                }
                else if (obj!= null && obj instanceof Boolean){
                    return (Boolean)obj;
                }
                return null;
            }
        },"http://tempuri.org/IServicio/VerificarUsuario");
    }
    
    public android.os.AsyncTask< Void, Void, MOCOperationResult< Boolean>> VerificarUsuarioAsync(final Integer _rut,final String _password)
    {
        return executeAsync(new MOCFunctions.IFunc< Boolean>() {
            public Boolean Func() throws java.lang.Exception {
                return VerificarUsuario( _rut,_password);
            }
        });
    }
    
    public MOCArrayOfUsuario ListarUsuarios( ) throws java.lang.Exception
    {
        return (MOCArrayOfUsuario)execute(new MOCIWcfMethod()
        {
            @Override
            public MOCExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              MOCExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "ListarUsuarios");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(MOCExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (MOCArrayOfUsuario)getResult(MOCArrayOfUsuario.class,__result,"ListarUsuariosResult",__envelope);
            }
        },"http://tempuri.org/IServicio/ListarUsuarios");
    }
    
    public android.os.AsyncTask< Void, Void, MOCOperationResult< MOCArrayOfUsuario>> ListarUsuariosAsync()
    {
        return executeAsync(new MOCFunctions.IFunc< MOCArrayOfUsuario>() {
            public MOCArrayOfUsuario Func() throws java.lang.Exception {
                return ListarUsuarios( );
            }
        });
    }
    
    public MOCUsuario BuscarUsuario(final Integer _rut ) throws java.lang.Exception
    {
        return (MOCUsuario)execute(new MOCIWcfMethod()
        {
            @Override
            public MOCExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              MOCExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "BuscarUsuario");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="_rut";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(_rut!=null?_rut:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(MOCExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (MOCUsuario)getResult(MOCUsuario.class,__result,"BuscarUsuarioResult",__envelope);
            }
        },"http://tempuri.org/IServicio/BuscarUsuario");
    }
    
    public android.os.AsyncTask< Void, Void, MOCOperationResult< MOCUsuario>> BuscarUsuarioAsync(final Integer _rut)
    {
        return executeAsync(new MOCFunctions.IFunc< MOCUsuario>() {
            public MOCUsuario Func() throws java.lang.Exception {
                return BuscarUsuario( _rut);
            }
        });
    }
    
    public Boolean CreateUsuario(final Integer _rut,final String _dv,final String _nombres,final String _apaterno,final String _amaterno,final String _password,final Integer _rol ) throws java.lang.Exception
    {
        return (Boolean)execute(new MOCIWcfMethod()
        {
            @Override
            public MOCExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              MOCExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "CreateUsuario");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="_rut";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(_rut!=null?_rut:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="_dv";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(_dv!=null?_dv:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="_nombres";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(_nombres!=null?_nombres:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="_apaterno";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(_apaterno!=null?_apaterno:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="_amaterno";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(_amaterno!=null?_amaterno:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="_password";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(_password!=null?_password:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="_rol";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(_rol!=null?_rol:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(MOCExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                SoapObject __soap=(SoapObject)__result;
                java.lang.Object obj = __soap.getProperty("CreateUsuarioResult");
                if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    return new Boolean(j.toString());
                }
                else if (obj!= null && obj instanceof Boolean){
                    return (Boolean)obj;
                }
                return null;
            }
        },"http://tempuri.org/IServicio/CreateUsuario");
    }
    
    public android.os.AsyncTask< Void, Void, MOCOperationResult< Boolean>> CreateUsuarioAsync(final Integer _rut,final String _dv,final String _nombres,final String _apaterno,final String _amaterno,final String _password,final Integer _rol)
    {
        return executeAsync(new MOCFunctions.IFunc< Boolean>() {
            public Boolean Func() throws java.lang.Exception {
                return CreateUsuario( _rut,_dv,_nombres,_apaterno,_amaterno,_password,_rol);
            }
        });
    }
    
    public Boolean UpdateUsuario(final Integer _rut,final String _nombres,final String _apaterno,final String _amaterno,final Integer _rol ) throws java.lang.Exception
    {
        return (Boolean)execute(new MOCIWcfMethod()
        {
            @Override
            public MOCExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              MOCExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "UpdateUsuario");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="_rut";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(_rut!=null?_rut:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="_nombres";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(_nombres!=null?_nombres:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="_apaterno";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(_apaterno!=null?_apaterno:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="_amaterno";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(_amaterno!=null?_amaterno:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="_rol";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(_rol!=null?_rol:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(MOCExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                SoapObject __soap=(SoapObject)__result;
                java.lang.Object obj = __soap.getProperty("UpdateUsuarioResult");
                if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    return new Boolean(j.toString());
                }
                else if (obj!= null && obj instanceof Boolean){
                    return (Boolean)obj;
                }
                return null;
            }
        },"http://tempuri.org/IServicio/UpdateUsuario");
    }
    
    public android.os.AsyncTask< Void, Void, MOCOperationResult< Boolean>> UpdateUsuarioAsync(final Integer _rut,final String _nombres,final String _apaterno,final String _amaterno,final Integer _rol)
    {
        return executeAsync(new MOCFunctions.IFunc< Boolean>() {
            public Boolean Func() throws java.lang.Exception {
                return UpdateUsuario( _rut,_nombres,_apaterno,_amaterno,_rol);
            }
        });
    }
    
    public Boolean SwitchStatusUsuario(final Integer _rut,final Boolean _enabled ) throws java.lang.Exception
    {
        return (Boolean)execute(new MOCIWcfMethod()
        {
            @Override
            public MOCExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              MOCExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "SwitchStatusUsuario");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="_rut";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(_rut!=null?_rut:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="_enabled";
                __info.type=PropertyInfo.BOOLEAN_CLASS;
                __info.setValue(_enabled!=null?_enabled:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(MOCExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                SoapObject __soap=(SoapObject)__result;
                java.lang.Object obj = __soap.getProperty("SwitchStatusUsuarioResult");
                if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    return new Boolean(j.toString());
                }
                else if (obj!= null && obj instanceof Boolean){
                    return (Boolean)obj;
                }
                return null;
            }
        },"http://tempuri.org/IServicio/SwitchStatusUsuario");
    }
    
    public android.os.AsyncTask< Void, Void, MOCOperationResult< Boolean>> SwitchStatusUsuarioAsync(final Integer _rut,final Boolean _enabled)
    {
        return executeAsync(new MOCFunctions.IFunc< Boolean>() {
            public Boolean Func() throws java.lang.Exception {
                return SwitchStatusUsuario( _rut,_enabled);
            }
        });
    }
    
    public Boolean UpdatePassword(final Integer _rut,final String _passAntigua,final String _passNueva ) throws java.lang.Exception
    {
        return (Boolean)execute(new MOCIWcfMethod()
        {
            @Override
            public MOCExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              MOCExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "UpdatePassword");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="_rut";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(_rut!=null?_rut:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="_passAntigua";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(_passAntigua!=null?_passAntigua:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="_passNueva";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(_passNueva!=null?_passNueva:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(MOCExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                SoapObject __soap=(SoapObject)__result;
                java.lang.Object obj = __soap.getProperty("UpdatePasswordResult");
                if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    return new Boolean(j.toString());
                }
                else if (obj!= null && obj instanceof Boolean){
                    return (Boolean)obj;
                }
                return null;
            }
        },"http://tempuri.org/IServicio/UpdatePassword");
    }
    
    public android.os.AsyncTask< Void, Void, MOCOperationResult< Boolean>> UpdatePasswordAsync(final Integer _rut,final String _passAntigua,final String _passNueva)
    {
        return executeAsync(new MOCFunctions.IFunc< Boolean>() {
            public Boolean Func() throws java.lang.Exception {
                return UpdatePassword( _rut,_passAntigua,_passNueva);
            }
        });
    }
    
    public Boolean hasPermission(final Integer _rut,final String _permission ) throws java.lang.Exception
    {
        return (Boolean)execute(new MOCIWcfMethod()
        {
            @Override
            public MOCExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              MOCExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "hasPermission");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="_rut";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(_rut!=null?_rut:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="_permission";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(_permission!=null?_permission:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(MOCExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                SoapObject __soap=(SoapObject)__result;
                java.lang.Object obj = __soap.getProperty("hasPermissionResult");
                if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    return new Boolean(j.toString());
                }
                else if (obj!= null && obj instanceof Boolean){
                    return (Boolean)obj;
                }
                return null;
            }
        },"http://tempuri.org/IServicio/hasPermission");
    }
    
    public android.os.AsyncTask< Void, Void, MOCOperationResult< Boolean>> hasPermissionAsync(final Integer _rut,final String _permission)
    {
        return executeAsync(new MOCFunctions.IFunc< Boolean>() {
            public Boolean Func() throws java.lang.Exception {
                return hasPermission( _rut,_permission);
            }
        });
    }
    
    public Boolean hasRole(final Integer _rut,final String _role ) throws java.lang.Exception
    {
        return (Boolean)execute(new MOCIWcfMethod()
        {
            @Override
            public MOCExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              MOCExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "hasRole");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="_rut";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(_rut!=null?_rut:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="_role";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(_role!=null?_role:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(MOCExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                SoapObject __soap=(SoapObject)__result;
                java.lang.Object obj = __soap.getProperty("hasRoleResult");
                if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    return new Boolean(j.toString());
                }
                else if (obj!= null && obj instanceof Boolean){
                    return (Boolean)obj;
                }
                return null;
            }
        },"http://tempuri.org/IServicio/hasRole");
    }
    
    public android.os.AsyncTask< Void, Void, MOCOperationResult< Boolean>> hasRoleAsync(final Integer _rut,final String _role)
    {
        return executeAsync(new MOCFunctions.IFunc< Boolean>() {
            public Boolean Func() throws java.lang.Exception {
                return hasRole( _rut,_role);
            }
        });
    }
    
    public Boolean ValidaRut(final String _rut,final String _dv ) throws java.lang.Exception
    {
        return (Boolean)execute(new MOCIWcfMethod()
        {
            @Override
            public MOCExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              MOCExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "ValidaRut");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="_rut";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(_rut!=null?_rut:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="_dv";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(_dv!=null?_dv:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(MOCExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                SoapObject __soap=(SoapObject)__result;
                java.lang.Object obj = __soap.getProperty("ValidaRutResult");
                if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    return new Boolean(j.toString());
                }
                else if (obj!= null && obj instanceof Boolean){
                    return (Boolean)obj;
                }
                return null;
            }
        },"http://tempuri.org/IServicio/ValidaRut");
    }
    
    public android.os.AsyncTask< Void, Void, MOCOperationResult< Boolean>> ValidaRutAsync(final String _rut,final String _dv)
    {
        return executeAsync(new MOCFunctions.IFunc< Boolean>() {
            public Boolean Func() throws java.lang.Exception {
                return ValidaRut( _rut,_dv);
            }
        });
    }
    
    public MOCArrayOfEmpresa ListarEmpresas( ) throws java.lang.Exception
    {
        return (MOCArrayOfEmpresa)execute(new MOCIWcfMethod()
        {
            @Override
            public MOCExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              MOCExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "ListarEmpresas");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(MOCExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (MOCArrayOfEmpresa)getResult(MOCArrayOfEmpresa.class,__result,"ListarEmpresasResult",__envelope);
            }
        },"http://tempuri.org/IServicio/ListarEmpresas");
    }
    
    public android.os.AsyncTask< Void, Void, MOCOperationResult< MOCArrayOfEmpresa>> ListarEmpresasAsync()
    {
        return executeAsync(new MOCFunctions.IFunc< MOCArrayOfEmpresa>() {
            public MOCArrayOfEmpresa Func() throws java.lang.Exception {
                return ListarEmpresas( );
            }
        });
    }
    
    public MOCArrayOfTalonario ListarTalonariosPorEmpresa(final Integer _rutEmpresa ) throws java.lang.Exception
    {
        return (MOCArrayOfTalonario)execute(new MOCIWcfMethod()
        {
            @Override
            public MOCExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              MOCExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "ListarTalonariosPorEmpresa");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="_rutEmpresa";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(_rutEmpresa!=null?_rutEmpresa:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(MOCExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (MOCArrayOfTalonario)getResult(MOCArrayOfTalonario.class,__result,"ListarTalonariosPorEmpresaResult",__envelope);
            }
        },"http://tempuri.org/IServicio/ListarTalonariosPorEmpresa");
    }
    
    public android.os.AsyncTask< Void, Void, MOCOperationResult< MOCArrayOfTalonario>> ListarTalonariosPorEmpresaAsync(final Integer _rutEmpresa)
    {
        return executeAsync(new MOCFunctions.IFunc< MOCArrayOfTalonario>() {
            public MOCArrayOfTalonario Func() throws java.lang.Exception {
                return ListarTalonariosPorEmpresa( _rutEmpresa);
            }
        });
    }
    
    public MOCEmpresa BuscarEmpresa(final Integer _rut ) throws java.lang.Exception
    {
        return (MOCEmpresa)execute(new MOCIWcfMethod()
        {
            @Override
            public MOCExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              MOCExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "BuscarEmpresa");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="_rut";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(_rut!=null?_rut:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(MOCExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (MOCEmpresa)getResult(MOCEmpresa.class,__result,"BuscarEmpresaResult",__envelope);
            }
        },"http://tempuri.org/IServicio/BuscarEmpresa");
    }
    
    public android.os.AsyncTask< Void, Void, MOCOperationResult< MOCEmpresa>> BuscarEmpresaAsync(final Integer _rut)
    {
        return executeAsync(new MOCFunctions.IFunc< MOCEmpresa>() {
            public MOCEmpresa Func() throws java.lang.Exception {
                return BuscarEmpresa( _rut);
            }
        });
    }
    
    public Boolean CreateEmpresa(final Integer _rut,final String _dv,final String _nombre,final Integer _rutUsuario ) throws java.lang.Exception
    {
        return (Boolean)execute(new MOCIWcfMethod()
        {
            @Override
            public MOCExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              MOCExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "CreateEmpresa");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="_rut";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(_rut!=null?_rut:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="_dv";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(_dv!=null?_dv:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="_nombre";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(_nombre!=null?_nombre:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="_rutUsuario";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(_rutUsuario!=null?_rutUsuario:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(MOCExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                SoapObject __soap=(SoapObject)__result;
                java.lang.Object obj = __soap.getProperty("CreateEmpresaResult");
                if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    return new Boolean(j.toString());
                }
                else if (obj!= null && obj instanceof Boolean){
                    return (Boolean)obj;
                }
                return null;
            }
        },"http://tempuri.org/IServicio/CreateEmpresa");
    }
    
    public android.os.AsyncTask< Void, Void, MOCOperationResult< Boolean>> CreateEmpresaAsync(final Integer _rut,final String _dv,final String _nombre,final Integer _rutUsuario)
    {
        return executeAsync(new MOCFunctions.IFunc< Boolean>() {
            public Boolean Func() throws java.lang.Exception {
                return CreateEmpresa( _rut,_dv,_nombre,_rutUsuario);
            }
        });
    }
    
    public Boolean UpdateEmpresa(final Integer _rut,final String _nombre,final Integer _rutUsuario ) throws java.lang.Exception
    {
        return (Boolean)execute(new MOCIWcfMethod()
        {
            @Override
            public MOCExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              MOCExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "UpdateEmpresa");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="_rut";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(_rut!=null?_rut:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="_nombre";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(_nombre!=null?_nombre:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="_rutUsuario";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(_rutUsuario!=null?_rutUsuario:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(MOCExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                SoapObject __soap=(SoapObject)__result;
                java.lang.Object obj = __soap.getProperty("UpdateEmpresaResult");
                if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    return new Boolean(j.toString());
                }
                else if (obj!= null && obj instanceof Boolean){
                    return (Boolean)obj;
                }
                return null;
            }
        },"http://tempuri.org/IServicio/UpdateEmpresa");
    }
    
    public android.os.AsyncTask< Void, Void, MOCOperationResult< Boolean>> UpdateEmpresaAsync(final Integer _rut,final String _nombre,final Integer _rutUsuario)
    {
        return executeAsync(new MOCFunctions.IFunc< Boolean>() {
            public Boolean Func() throws java.lang.Exception {
                return UpdateEmpresa( _rut,_nombre,_rutUsuario);
            }
        });
    }
    
    public Boolean SwitchStatusEmpresa(final Integer _rut,final Boolean _enabled ) throws java.lang.Exception
    {
        return (Boolean)execute(new MOCIWcfMethod()
        {
            @Override
            public MOCExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              MOCExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "SwitchStatusEmpresa");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="_rut";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(_rut!=null?_rut:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="_enabled";
                __info.type=PropertyInfo.BOOLEAN_CLASS;
                __info.setValue(_enabled!=null?_enabled:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(MOCExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                SoapObject __soap=(SoapObject)__result;
                java.lang.Object obj = __soap.getProperty("SwitchStatusEmpresaResult");
                if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    return new Boolean(j.toString());
                }
                else if (obj!= null && obj instanceof Boolean){
                    return (Boolean)obj;
                }
                return null;
            }
        },"http://tempuri.org/IServicio/SwitchStatusEmpresa");
    }
    
    public android.os.AsyncTask< Void, Void, MOCOperationResult< Boolean>> SwitchStatusEmpresaAsync(final Integer _rut,final Boolean _enabled)
    {
        return executeAsync(new MOCFunctions.IFunc< Boolean>() {
            public Boolean Func() throws java.lang.Exception {
                return SwitchStatusEmpresa( _rut,_enabled);
            }
        });
    }
    
    public MOCArrayOfHistorialPrecio ListarHistorialPrecio( ) throws java.lang.Exception
    {
        return (MOCArrayOfHistorialPrecio)execute(new MOCIWcfMethod()
        {
            @Override
            public MOCExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              MOCExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "ListarHistorialPrecio");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(MOCExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (MOCArrayOfHistorialPrecio)getResult(MOCArrayOfHistorialPrecio.class,__result,"ListarHistorialPrecioResult",__envelope);
            }
        },"http://tempuri.org/IServicio/ListarHistorialPrecio");
    }
    
    public android.os.AsyncTask< Void, Void, MOCOperationResult< MOCArrayOfHistorialPrecio>> ListarHistorialPrecioAsync()
    {
        return executeAsync(new MOCFunctions.IFunc< MOCArrayOfHistorialPrecio>() {
            public MOCArrayOfHistorialPrecio Func() throws java.lang.Exception {
                return ListarHistorialPrecio( );
            }
        });
    }
    
    public MOCArrayOfHistorialPrecio ListarHistorialPrecioPorCombustible(final Integer _idCombustible ) throws java.lang.Exception
    {
        return (MOCArrayOfHistorialPrecio)execute(new MOCIWcfMethod()
        {
            @Override
            public MOCExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              MOCExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "ListarHistorialPrecioPorCombustible");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="_idCombustible";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(_idCombustible!=null?_idCombustible:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(MOCExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (MOCArrayOfHistorialPrecio)getResult(MOCArrayOfHistorialPrecio.class,__result,"ListarHistorialPrecioPorCombustibleResult",__envelope);
            }
        },"http://tempuri.org/IServicio/ListarHistorialPrecioPorCombustible");
    }
    
    public android.os.AsyncTask< Void, Void, MOCOperationResult< MOCArrayOfHistorialPrecio>> ListarHistorialPrecioPorCombustibleAsync(final Integer _idCombustible)
    {
        return executeAsync(new MOCFunctions.IFunc< MOCArrayOfHistorialPrecio>() {
            public MOCArrayOfHistorialPrecio Func() throws java.lang.Exception {
                return ListarHistorialPrecioPorCombustible( _idCombustible);
            }
        });
    }
    
    public MOCHistorialPrecio BuscarHistorialPrecio(final Integer _id ) throws java.lang.Exception
    {
        return (MOCHistorialPrecio)execute(new MOCIWcfMethod()
        {
            @Override
            public MOCExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              MOCExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "BuscarHistorialPrecio");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="_id";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(_id!=null?_id:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(MOCExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (MOCHistorialPrecio)getResult(MOCHistorialPrecio.class,__result,"BuscarHistorialPrecioResult",__envelope);
            }
        },"http://tempuri.org/IServicio/BuscarHistorialPrecio");
    }
    
    public android.os.AsyncTask< Void, Void, MOCOperationResult< MOCHistorialPrecio>> BuscarHistorialPrecioAsync(final Integer _id)
    {
        return executeAsync(new MOCFunctions.IFunc< MOCHistorialPrecio>() {
            public MOCHistorialPrecio Func() throws java.lang.Exception {
                return BuscarHistorialPrecio( _id);
            }
        });
    }
    
    public BigDecimal BuscarPrecioActualDeCombustible(final Integer _idCombustible ) throws java.lang.Exception
    {
        return (BigDecimal)execute(new MOCIWcfMethod()
        {
            @Override
            public MOCExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              MOCExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "BuscarPrecioActualDeCombustible");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="_idCombustible";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(_idCombustible!=null?_idCombustible:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(MOCExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                SoapObject __soap=(SoapObject)__result;
                java.lang.Object obj = __soap.getProperty("BuscarPrecioActualDeCombustibleResult");
                if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    return new BigDecimal(j.toString());
                }
                else if (obj!= null && obj instanceof BigDecimal){
                    return (BigDecimal)obj;
                }
                return null;
            }
        },"http://tempuri.org/IServicio/BuscarPrecioActualDeCombustible");
    }
    
    public android.os.AsyncTask< Void, Void, MOCOperationResult< BigDecimal>> BuscarPrecioActualDeCombustibleAsync(final Integer _idCombustible)
    {
        return executeAsync(new MOCFunctions.IFunc< BigDecimal>() {
            public BigDecimal Func() throws java.lang.Exception {
                return BuscarPrecioActualDeCombustible( _idCombustible);
            }
        });
    }
    
    public Boolean CreateHistorialPrecioCombustible(final Integer _id,final java.util.Date _fecha,final BigDecimal _precio,final Integer _idCombustible ) throws java.lang.Exception
    {
        return (Boolean)execute(new MOCIWcfMethod()
        {
            @Override
            public MOCExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              MOCExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "CreateHistorialPrecioCombustible");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="_id";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(_id!=null?_id:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="_fecha";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(_fecha!=null?MOCHelper.getDateTimeFormat().format(_fecha):SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="_precio";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(_precio!=null?_precio.toString():SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="_idCombustible";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(_idCombustible!=null?_idCombustible:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(MOCExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                SoapObject __soap=(SoapObject)__result;
                java.lang.Object obj = __soap.getProperty("CreateHistorialPrecioCombustibleResult");
                if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    return new Boolean(j.toString());
                }
                else if (obj!= null && obj instanceof Boolean){
                    return (Boolean)obj;
                }
                return null;
            }
        },"http://tempuri.org/IServicio/CreateHistorialPrecioCombustible");
    }
    
    public android.os.AsyncTask< Void, Void, MOCOperationResult< Boolean>> CreateHistorialPrecioCombustibleAsync(final Integer _id,final java.util.Date _fecha,final BigDecimal _precio,final Integer _idCombustible)
    {
        return executeAsync(new MOCFunctions.IFunc< Boolean>() {
            public Boolean Func() throws java.lang.Exception {
                return CreateHistorialPrecioCombustible( _id,_fecha,_precio,_idCombustible);
            }
        });
    }
    
    public Boolean UpdateHistorialPrecioCombustible(final Integer _id,final BigDecimal _precio,final Integer _idCombustible ) throws java.lang.Exception
    {
        return (Boolean)execute(new MOCIWcfMethod()
        {
            @Override
            public MOCExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              MOCExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "UpdateHistorialPrecioCombustible");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="_id";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(_id!=null?_id:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="_precio";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(_precio!=null?_precio.toString():SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="_idCombustible";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(_idCombustible!=null?_idCombustible:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(MOCExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                SoapObject __soap=(SoapObject)__result;
                java.lang.Object obj = __soap.getProperty("UpdateHistorialPrecioCombustibleResult");
                if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    return new Boolean(j.toString());
                }
                else if (obj!= null && obj instanceof Boolean){
                    return (Boolean)obj;
                }
                return null;
            }
        },"http://tempuri.org/IServicio/UpdateHistorialPrecioCombustible");
    }
    
    public android.os.AsyncTask< Void, Void, MOCOperationResult< Boolean>> UpdateHistorialPrecioCombustibleAsync(final Integer _id,final BigDecimal _precio,final Integer _idCombustible)
    {
        return executeAsync(new MOCFunctions.IFunc< Boolean>() {
            public Boolean Func() throws java.lang.Exception {
                return UpdateHistorialPrecioCombustible( _id,_precio,_idCombustible);
            }
        });
    }
    
    public MOCArrayOfCombustible ListarCombustibles( ) throws java.lang.Exception
    {
        return (MOCArrayOfCombustible)execute(new MOCIWcfMethod()
        {
            @Override
            public MOCExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              MOCExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "ListarCombustibles");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(MOCExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (MOCArrayOfCombustible)getResult(MOCArrayOfCombustible.class,__result,"ListarCombustiblesResult",__envelope);
            }
        },"http://tempuri.org/IServicio/ListarCombustibles");
    }
    
    public android.os.AsyncTask< Void, Void, MOCOperationResult< MOCArrayOfCombustible>> ListarCombustiblesAsync()
    {
        return executeAsync(new MOCFunctions.IFunc< MOCArrayOfCombustible>() {
            public MOCArrayOfCombustible Func() throws java.lang.Exception {
                return ListarCombustibles( );
            }
        });
    }
    
    public MOCCombustible BuscarCombustible(final Integer _idCombustible ) throws java.lang.Exception
    {
        return (MOCCombustible)execute(new MOCIWcfMethod()
        {
            @Override
            public MOCExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              MOCExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "BuscarCombustible");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="_idCombustible";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(_idCombustible!=null?_idCombustible:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(MOCExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (MOCCombustible)getResult(MOCCombustible.class,__result,"BuscarCombustibleResult",__envelope);
            }
        },"http://tempuri.org/IServicio/BuscarCombustible");
    }
    
    public android.os.AsyncTask< Void, Void, MOCOperationResult< MOCCombustible>> BuscarCombustibleAsync(final Integer _idCombustible)
    {
        return executeAsync(new MOCFunctions.IFunc< MOCCombustible>() {
            public MOCCombustible Func() throws java.lang.Exception {
                return BuscarCombustible( _idCombustible);
            }
        });
    }
    
    public String BuscarCombustiblesPorSurtidor(final String _idSurtidor ) throws java.lang.Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;    
    }
    
    public android.os.AsyncTask< Void, Void, MOCOperationResult< String>> BuscarCombustiblesPorSurtidorAsync(final String _idSurtidor)
    {
        return executeAsync(new MOCFunctions.IFunc< String>() {
            public String Func() throws java.lang.Exception {
                return BuscarCombustiblesPorSurtidor( _idSurtidor);
            }
        });
    }
    
    public String TotalLitosPorCombustible(final String _idCombustible ) throws java.lang.Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;    
    }
    
    public android.os.AsyncTask< Void, Void, MOCOperationResult< String>> TotalLitosPorCombustibleAsync(final String _idCombustible)
    {
        return executeAsync(new MOCFunctions.IFunc< String>() {
            public String Func() throws java.lang.Exception {
                return TotalLitosPorCombustible( _idCombustible);
            }
        });
    }
    
    public String CantidadDeCombustiblePorSurtidor(final String _idCombustible,final String _idSurtidor ) throws java.lang.Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;    
    }
    
    public android.os.AsyncTask< Void, Void, MOCOperationResult< String>> CantidadDeCombustiblePorSurtidorAsync(final String _idCombustible,final String _idSurtidor)
    {
        return executeAsync(new MOCFunctions.IFunc< String>() {
            public String Func() throws java.lang.Exception {
                return CantidadDeCombustiblePorSurtidor( _idCombustible,_idSurtidor);
            }
        });
    }
    
    public String CreateCombustible(final String _id,final String _nombre ) throws java.lang.Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;    
    }
    
    public android.os.AsyncTask< Void, Void, MOCOperationResult< String>> CreateCombustibleAsync(final String _id,final String _nombre)
    {
        return executeAsync(new MOCFunctions.IFunc< String>() {
            public String Func() throws java.lang.Exception {
                return CreateCombustible( _id,_nombre);
            }
        });
    }
    
    public String SwitchStatusCombustible(final String _id,final String _enabled ) throws java.lang.Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;    
    }
    
    public android.os.AsyncTask< Void, Void, MOCOperationResult< String>> SwitchStatusCombustibleAsync(final String _id,final String _enabled)
    {
        return executeAsync(new MOCFunctions.IFunc< String>() {
            public String Func() throws java.lang.Exception {
                return SwitchStatusCombustible( _id,_enabled);
            }
        });
    }
    
    public String ListarSurtidores( ) throws java.lang.Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;    
    }
    
    public android.os.AsyncTask< Void, Void, MOCOperationResult< String>> ListarSurtidoresAsync()
    {
        return executeAsync(new MOCFunctions.IFunc< String>() {
            public String Func() throws java.lang.Exception {
                return ListarSurtidores( );
            }
        });
    }
    
    public String BuscarSurtidor(final String _id ) throws java.lang.Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;    
    }
    
    public android.os.AsyncTask< Void, Void, MOCOperationResult< String>> BuscarSurtidorAsync(final String _id)
    {
        return executeAsync(new MOCFunctions.IFunc< String>() {
            public String Func() throws java.lang.Exception {
                return BuscarSurtidor( _id);
            }
        });
    }
    
    public String CreateSurtidor(final String _id ) throws java.lang.Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;    
    }
    
    public android.os.AsyncTask< Void, Void, MOCOperationResult< String>> CreateSurtidorAsync(final String _id)
    {
        return executeAsync(new MOCFunctions.IFunc< String>() {
            public String Func() throws java.lang.Exception {
                return CreateSurtidor( _id);
            }
        });
    }
    
    public String SwitchStatusSurtidor(final String _id,final String _enabled ) throws java.lang.Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;    
    }
    
    public android.os.AsyncTask< Void, Void, MOCOperationResult< String>> SwitchStatusSurtidorAsync(final String _id,final String _enabled)
    {
        return executeAsync(new MOCFunctions.IFunc< String>() {
            public String Func() throws java.lang.Exception {
                return SwitchStatusSurtidor( _id,_enabled);
            }
        });
    }
    
    public String CargarORemoverCombusible(final String _idSurtidor,final String _litros,final String _idCombustible ) throws java.lang.Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;    
    }
    
    public android.os.AsyncTask< Void, Void, MOCOperationResult< String>> CargarORemoverCombusibleAsync(final String _idSurtidor,final String _litros,final String _idCombustible)
    {
        return executeAsync(new MOCFunctions.IFunc< String>() {
            public String Func() throws java.lang.Exception {
                return CargarORemoverCombusible( _idSurtidor,_litros,_idCombustible);
            }
        });
    }
    
    public String ListarTalonarios( ) throws java.lang.Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;    
    }
    
    public android.os.AsyncTask< Void, Void, MOCOperationResult< String>> ListarTalonariosAsync()
    {
        return executeAsync(new MOCFunctions.IFunc< String>() {
            public String Func() throws java.lang.Exception {
                return ListarTalonarios( );
            }
        });
    }
    
    public String BuscarTalonario(final String _id ) throws java.lang.Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;    
    }
    
    public android.os.AsyncTask< Void, Void, MOCOperationResult< String>> BuscarTalonarioAsync(final String _id)
    {
        return executeAsync(new MOCFunctions.IFunc< String>() {
            public String Func() throws java.lang.Exception {
                return BuscarTalonario( _id);
            }
        });
    }
    
    public String BuscarTalonarioDeVale(final String _idVale ) throws java.lang.Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;    
    }
    
    public android.os.AsyncTask< Void, Void, MOCOperationResult< String>> BuscarTalonarioDeValeAsync(final String _idVale)
    {
        return executeAsync(new MOCFunctions.IFunc< String>() {
            public String Func() throws java.lang.Exception {
                return BuscarTalonarioDeVale( _idVale);
            }
        });
    }
    
    public String CreateTalonario(final String _id,final String _fechaEntrega,final String _numComprobanteTransaccion,final String _rutEmpresa ) throws java.lang.Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;    
    }
    
    public android.os.AsyncTask< Void, Void, MOCOperationResult< String>> CreateTalonarioAsync(final String _id,final String _fechaEntrega,final String _numComprobanteTransaccion,final String _rutEmpresa)
    {
        return executeAsync(new MOCFunctions.IFunc< String>() {
            public String Func() throws java.lang.Exception {
                return CreateTalonario( _id,_fechaEntrega,_numComprobanteTransaccion,_rutEmpresa);
            }
        });
    }
    
    public String UpdateTalonario(final String _id,final String _fechaEntrega,final String _numComprobanteTransaccion,final String _rutEmpresa ) throws java.lang.Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;    
    }
    
    public android.os.AsyncTask< Void, Void, MOCOperationResult< String>> UpdateTalonarioAsync(final String _id,final String _fechaEntrega,final String _numComprobanteTransaccion,final String _rutEmpresa)
    {
        return executeAsync(new MOCFunctions.IFunc< String>() {
            public String Func() throws java.lang.Exception {
                return UpdateTalonario( _id,_fechaEntrega,_numComprobanteTransaccion,_rutEmpresa);
            }
        });
    }
    
    public String SwitchStatusTalonario(final String _id,final String _enabled ) throws java.lang.Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;    
    }
    
    public android.os.AsyncTask< Void, Void, MOCOperationResult< String>> SwitchStatusTalonarioAsync(final String _id,final String _enabled)
    {
        return executeAsync(new MOCFunctions.IFunc< String>() {
            public String Func() throws java.lang.Exception {
                return SwitchStatusTalonario( _id,_enabled);
            }
        });
    }
    
    public String BuscarVale(final String _id ) throws java.lang.Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;    
    }
    
    public android.os.AsyncTask< Void, Void, MOCOperationResult< String>> BuscarValeAsync(final String _id)
    {
        return executeAsync(new MOCFunctions.IFunc< String>() {
            public String Func() throws java.lang.Exception {
                return BuscarVale( _id);
            }
        });
    }
    
    public String BuscarValesPorTalonario(final String _idTalonario ) throws java.lang.Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;    
    }
    
    public android.os.AsyncTask< Void, Void, MOCOperationResult< String>> BuscarValesPorTalonarioAsync(final String _idTalonario)
    {
        return executeAsync(new MOCFunctions.IFunc< String>() {
            public String Func() throws java.lang.Exception {
                return BuscarValesPorTalonario( _idTalonario);
            }
        });
    }
    
    public String CreateVale(final String _id,final String _cantLitros,final String _idTalonario ) throws java.lang.Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;    
    }
    
    public android.os.AsyncTask< Void, Void, MOCOperationResult< String>> CreateValeAsync(final String _id,final String _cantLitros,final String _idTalonario)
    {
        return executeAsync(new MOCFunctions.IFunc< String>() {
            public String Func() throws java.lang.Exception {
                return CreateVale( _id,_cantLitros,_idTalonario);
            }
        });
    }
    
    public String MassCreateVale(final String _cantLitros,final String _idTalonario,final String _cantidad ) throws java.lang.Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;    
    }
    
    public android.os.AsyncTask< Void, Void, MOCOperationResult< String>> MassCreateValeAsync(final String _cantLitros,final String _idTalonario,final String _cantidad)
    {
        return executeAsync(new MOCFunctions.IFunc< String>() {
            public String Func() throws java.lang.Exception {
                return MassCreateVale( _cantLitros,_idTalonario,_cantidad);
            }
        });
    }
    
    public String UpdateVale(final String _id,final String _cantidadLitos ) throws java.lang.Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;    
    }
    
    public android.os.AsyncTask< Void, Void, MOCOperationResult< String>> UpdateValeAsync(final String _id,final String _cantidadLitos)
    {
        return executeAsync(new MOCFunctions.IFunc< String>() {
            public String Func() throws java.lang.Exception {
                return UpdateVale( _id,_cantidadLitos);
            }
        });
    }
    
    public String SwitchStatusVale(final String _id,final String _enabled ) throws java.lang.Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;    
    }
    
    public android.os.AsyncTask< Void, Void, MOCOperationResult< String>> SwitchStatusValeAsync(final String _id,final String _enabled)
    {
        return executeAsync(new MOCFunctions.IFunc< String>() {
            public String Func() throws java.lang.Exception {
                return SwitchStatusVale( _id,_enabled);
            }
        });
    }
    
    public String ListarBeneficiarios( ) throws java.lang.Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;    
    }
    
    public android.os.AsyncTask< Void, Void, MOCOperationResult< String>> ListarBeneficiariosAsync()
    {
        return executeAsync(new MOCFunctions.IFunc< String>() {
            public String Func() throws java.lang.Exception {
                return ListarBeneficiarios( );
            }
        });
    }
    
    public String BuscarBeneficiario(final String _id ) throws java.lang.Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;    
    }
    
    public android.os.AsyncTask< Void, Void, MOCOperationResult< String>> BuscarBeneficiarioAsync(final String _id)
    {
        return executeAsync(new MOCFunctions.IFunc< String>() {
            public String Func() throws java.lang.Exception {
                return BuscarBeneficiario( _id);
            }
        });
    }
    
    public String CreateBeneficiario(final String _id,final String _rut,final String _dv,final String _tope_litros,final String _limite_vigencia,final String _nombreEmpresa,final String _estado,final String _rol ) throws java.lang.Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;    
    }
    
    public android.os.AsyncTask< Void, Void, MOCOperationResult< String>> CreateBeneficiarioAsync(final String _id,final String _rut,final String _dv,final String _tope_litros,final String _limite_vigencia,final String _nombreEmpresa,final String _estado,final String _rol)
    {
        return executeAsync(new MOCFunctions.IFunc< String>() {
            public String Func() throws java.lang.Exception {
                return CreateBeneficiario( _id,_rut,_dv,_tope_litros,_limite_vigencia,_nombreEmpresa,_estado,_rol);
            }
        });
    }
    
    public String UpdateBeneficiario(final String _id,final String _tope_litros,final String _limiteVigencia,final String _nombreEmpresa ) throws java.lang.Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;    
    }
    
    public android.os.AsyncTask< Void, Void, MOCOperationResult< String>> UpdateBeneficiarioAsync(final String _id,final String _tope_litros,final String _limiteVigencia,final String _nombreEmpresa)
    {
        return executeAsync(new MOCFunctions.IFunc< String>() {
            public String Func() throws java.lang.Exception {
                return UpdateBeneficiario( _id,_tope_litros,_limiteVigencia,_nombreEmpresa);
            }
        });
    }
    
    public String SwitchStatusBeneficiario(final String _id,final String _enabled ) throws java.lang.Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;    
    }
    
    public android.os.AsyncTask< Void, Void, MOCOperationResult< String>> SwitchStatusBeneficiarioAsync(final String _id,final String _enabled)
    {
        return executeAsync(new MOCFunctions.IFunc< String>() {
            public String Func() throws java.lang.Exception {
                return SwitchStatusBeneficiario( _id,_enabled);
            }
        });
    }
    
    public String BeneficiarioIsOverLimit(final String _idBeneficiario,final String _cantidadLitros ) throws java.lang.Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;    
    }
    
    public android.os.AsyncTask< Void, Void, MOCOperationResult< String>> BeneficiarioIsOverLimitAsync(final String _idBeneficiario,final String _cantidadLitros)
    {
        return executeAsync(new MOCFunctions.IFunc< String>() {
            public String Func() throws java.lang.Exception {
                return BeneficiarioIsOverLimit( _idBeneficiario,_cantidadLitros);
            }
        });
    }
    
    public String ListarAnulaciones( ) throws java.lang.Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;    
    }
    
    public android.os.AsyncTask< Void, Void, MOCOperationResult< String>> ListarAnulacionesAsync()
    {
        return executeAsync(new MOCFunctions.IFunc< String>() {
            public String Func() throws java.lang.Exception {
                return ListarAnulaciones( );
            }
        });
    }
    
    public String BuscarAnulacion(final String _id ) throws java.lang.Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;    
    }
    
    public android.os.AsyncTask< Void, Void, MOCOperationResult< String>> BuscarAnulacionAsync(final String _id)
    {
        return executeAsync(new MOCFunctions.IFunc< String>() {
            public String Func() throws java.lang.Exception {
                return BuscarAnulacion( _id);
            }
        });
    }
    
    public String UpdateAnulacion(final String _id,final String _razon,final String _rutUsuario ) throws java.lang.Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;    
    }
    
    public android.os.AsyncTask< Void, Void, MOCOperationResult< String>> UpdateAnulacionAsync(final String _id,final String _razon,final String _rutUsuario)
    {
        return executeAsync(new MOCFunctions.IFunc< String>() {
            public String Func() throws java.lang.Exception {
                return UpdateAnulacion( _id,_razon,_rutUsuario);
            }
        });
    }

    
    protected java.lang.Object execute(MOCIWcfMethod wcfMethod,String methodName) throws java.lang.Exception
    {
        org.ksoap2.transport.Transport __httpTransport=createTransport();
        __httpTransport.debug=enableLogging;
        MOCExtendedSoapSerializationEnvelope __envelope=wcfMethod.CreateSoapEnvelope();
        try
        {
            sendRequest(methodName, __envelope, __httpTransport);
            
        }
        finally {
            if (__httpTransport.debug) {
                if (__httpTransport.requestDump != null) {
                    android.util.Log.i("requestDump",__httpTransport.requestDump);    
                    
                }
                if (__httpTransport.responseDump != null) {
                    android.util.Log.i("responseDump",__httpTransport.responseDump);
                }
            }
        }
        java.lang.Object __retObj = __envelope.bodyIn;
        if (__retObj instanceof org.ksoap2.SoapFault){
            org.ksoap2.SoapFault __fault = (org.ksoap2.SoapFault)__retObj;
            throw convertToException(__fault,__envelope);
        }else{
            return wcfMethod.ProcessResult(__envelope,__retObj);
        }
    }
    
    protected < T> android.os.AsyncTask< Void, Void, MOCOperationResult< T>>  executeAsync(final MOCFunctions.IFunc< T> func)
    {
        return new android.os.AsyncTask< Void, Void, MOCOperationResult< T>>()
        {
            @Override
            protected void onPreExecute() {
                callback.Starting();
            };
            @Override
            protected MOCOperationResult< T> doInBackground(Void... params) {
                MOCOperationResult< T> result = new MOCOperationResult< T>();
                try
                {
                    result.Result= func.Func();
                }
                catch(java.lang.Exception ex)
                {
                    ex.printStackTrace();
                    result.Exception=ex;
                }
                return result;
            }
            
            @Override
            protected void onPostExecute(MOCOperationResult< T> result)
            {
                callback.Completed(result);
            }
        }.execute();
    }
        
    java.lang.Exception convertToException(org.ksoap2.SoapFault fault,MOCExtendedSoapSerializationEnvelope envelope)
    {

        return new java.lang.Exception(fault.faultstring);
    }
}


