package cl.fap.tecnobencina.clases.service;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.5.6.0
//
// Created by Quasar Development at 15/06/2016
//
//---------------------------------------------------





public class MOCEnums
{

    public enum EstadoVenta
    {
        
        sin_confirmar(0),
        
        confirmada(1),
        
        anulada(2);
        
        private int code;
        
        EstadoVenta(int code ){
            this.code = code;
        }
    
        public int getCode(){
		    return code;
	    }
    

        public static EstadoVenta fromString(String str)
        {
            if (str.equals("sin_confirmar"))
                return sin_confirmar;
            if (str.equals("confirmada"))
                return confirmada;
            if (str.equals("anulada"))
                return anulada;
		    return null;
        }
    }

    public enum CantidadLitros
    {
        
        diez(10),
        
        veinte(20),
        
        treinta(30);
        
        private int code;
        
        CantidadLitros(int code ){
            this.code = code;
        }
    
        public int getCode(){
		    return code;
	    }
    

        public static CantidadLitros fromString(String str)
        {
            if (str.equals("diez"))
                return diez;
            if (str.equals("veinte"))
                return veinte;
            if (str.equals("treinta"))
                return treinta;
		    return null;
        }
    }

}