package cl.fap.tecnobencina.clases.service;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.5.6.0
//
// Created by Quasar Development at 15/06/2016
//
//---------------------------------------------------



public interface MOCIServiceEvents
{
    public void Starting();
    public void Completed(MOCOperationResult result);
}
