package cl.fap.tecnobencina.clases.service;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.5.6.0
//
// Created by Quasar Development at 15/06/2016
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class MOCVenta extends AttributeContainer implements KvmSerializable
{

    
    public MOCAnulacion anulacion;
    
    public MOCBeneficiarioCredito beneficiarioCredito;
    
    public MOCCombustible combustible;
    
    public MOCEnums.EstadoVenta estado;
    
    public java.util.Date fecha;
    
    public Integer id;
    
    public Integer litros;
    
    public Integer monto;
    
    public MOCSurtidor surtidor;
    
    public MOCUsuario usuario;
    
    public MOCVale vale;

    public MOCVenta ()
    {
    }

    public MOCVenta (java.lang.Object paramObj,MOCExtendedSoapSerializationEnvelope __envelope)
    {
	    
	    if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;


        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                //if you have compilation error here, please use a ksoap2.jar and ExKsoap2.jar from libs folder (in the generated zip file)
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                java.lang.Object obj = info.getValue(); 
                if (info.name.equals("anulacion"))
                {
                    if(obj!=null)
                    {
                        java.lang.Object j = obj;
                        this.anulacion = (MOCAnulacion)__envelope.get(j,MOCAnulacion.class);
                    }
                    continue;
                }
                if (info.name.equals("beneficiarioCredito"))
                {
                    if(obj!=null)
                    {
                        java.lang.Object j = obj;
                        this.beneficiarioCredito = (MOCBeneficiarioCredito)__envelope.get(j,MOCBeneficiarioCredito.class);
                    }
                    continue;
                }
                if (info.name.equals("combustible"))
                {
                    if(obj!=null)
                    {
                        java.lang.Object j = obj;
                        this.combustible = (MOCCombustible)__envelope.get(j,MOCCombustible.class);
                    }
                    continue;
                }
                if (info.name.equals("estado"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.estado = MOCEnums.EstadoVenta.fromString(j.toString());
                            }
                        }
                        else if (obj instanceof MOCEnums.EstadoVenta){
                            this.estado = (MOCEnums.EstadoVenta)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("fecha"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.fecha = MOCHelper.ConvertFromWebService(j.toString());
                            }
                        }
                        else if (obj instanceof java.util.Date){
                            this.fecha = (java.util.Date)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("id"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.id = Integer.parseInt(j.toString());
                            }
                        }
                        else if (obj instanceof Integer){
                            this.id = (Integer)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("litros"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.litros = Integer.parseInt(j.toString());
                            }
                        }
                        else if (obj instanceof Integer){
                            this.litros = (Integer)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("monto"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.monto = Integer.parseInt(j.toString());
                            }
                        }
                        else if (obj instanceof Integer){
                            this.monto = (Integer)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("surtidor"))
                {
                    if(obj!=null)
                    {
                        java.lang.Object j = obj;
                        this.surtidor = (MOCSurtidor)__envelope.get(j,MOCSurtidor.class);
                    }
                    continue;
                }
                if (info.name.equals("usuario"))
                {
                    if(obj!=null)
                    {
                        java.lang.Object j = obj;
                        this.usuario = (MOCUsuario)__envelope.get(j,MOCUsuario.class);
                    }
                    continue;
                }
                if (info.name.equals("vale"))
                {
                    if(obj!=null)
                    {
                        java.lang.Object j = obj;
                        this.vale = (MOCVale)__envelope.get(j,MOCVale.class);
                    }
                    continue;
                }

            }

        }



    }

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.anulacion!=null?this.anulacion:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1)
        {
            return this.beneficiarioCredito!=null?this.beneficiarioCredito:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return this.combustible!=null?this.combustible:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==3)
        {
            return this.estado!=null?this.estado.toString():SoapPrimitive.NullSkip;
        }
        if(propertyIndex==4)
        {
            return this.fecha!=null?MOCHelper.getDateTimeFormat().format(this.fecha):SoapPrimitive.NullSkip;
        }
        if(propertyIndex==5)
        {
            return this.id!=null?this.id:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==6)
        {
            return this.litros!=null?this.litros:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==7)
        {
            return this.monto!=null?this.monto:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==8)
        {
            return this.surtidor!=null?this.surtidor:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==9)
        {
            return this.usuario!=null?this.usuario:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==10)
        {
            return this.vale!=null?this.vale:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 11;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = MOCAnulacion.class;
            info.name = "anulacion";
            info.namespace= "http://schemas.datacontract.org/2004/07/TecnoBencina.Negocio";
        }
        if(propertyIndex==1)
        {
            info.type = MOCBeneficiarioCredito.class;
            info.name = "beneficiarioCredito";
            info.namespace= "http://schemas.datacontract.org/2004/07/TecnoBencina.Negocio";
        }
        if(propertyIndex==2)
        {
            info.type = MOCCombustible.class;
            info.name = "combustible";
            info.namespace= "http://schemas.datacontract.org/2004/07/TecnoBencina.Negocio";
        }
        if(propertyIndex==3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "estado";
            info.namespace= "http://schemas.datacontract.org/2004/07/TecnoBencina.Negocio";
        }
        if(propertyIndex==4)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "fecha";
            info.namespace= "http://schemas.datacontract.org/2004/07/TecnoBencina.Negocio";
        }
        if(propertyIndex==5)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "id";
            info.namespace= "http://schemas.datacontract.org/2004/07/TecnoBencina.Negocio";
        }
        if(propertyIndex==6)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "litros";
            info.namespace= "http://schemas.datacontract.org/2004/07/TecnoBencina.Negocio";
        }
        if(propertyIndex==7)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "monto";
            info.namespace= "http://schemas.datacontract.org/2004/07/TecnoBencina.Negocio";
        }
        if(propertyIndex==8)
        {
            info.type = MOCSurtidor.class;
            info.name = "surtidor";
            info.namespace= "http://schemas.datacontract.org/2004/07/TecnoBencina.Negocio";
        }
        if(propertyIndex==9)
        {
            info.type = MOCUsuario.class;
            info.name = "usuario";
            info.namespace= "http://schemas.datacontract.org/2004/07/TecnoBencina.Negocio";
        }
        if(propertyIndex==10)
        {
            info.type = MOCVale.class;
            info.name = "vale";
            info.namespace= "http://schemas.datacontract.org/2004/07/TecnoBencina.Negocio";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

}
